// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: gnomobiletypes.proto

package gnomobiletypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyType int32

const (
	KeyType_TypeLocal   KeyType = 0
	KeyType_TypeLedger  KeyType = 1
	KeyType_TypeOffline KeyType = 2
	KeyType_TypeMulti   KeyType = 3
)

// Enum value maps for KeyType.
var (
	KeyType_name = map[int32]string{
		0: "TypeLocal",
		1: "TypeLedger",
		2: "TypeOffline",
		3: "TypeMulti",
	}
	KeyType_value = map[string]int32{
		"TypeLocal":   0,
		"TypeLedger":  1,
		"TypeOffline": 2,
		"TypeMulti":   3,
	}
)

func (x KeyType) Enum() *KeyType {
	p := new(KeyType)
	*p = x
	return p
}

func (x KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_gnomobiletypes_proto_enumTypes[0].Descriptor()
}

func (KeyType) Type() protoreflect.EnumType {
	return &file_gnomobiletypes_proto_enumTypes[0]
}

func (x KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyType.Descriptor instead.
func (KeyType) EnumDescriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{0}
}

type ErrCode int32

const (
	ErrCode_Undefined               ErrCode = 0 // default value, should never be set manually
	ErrCode_TODO                    ErrCode = 1 // indicates that you plan to create an error later
	ErrCode_ErrNotImplemented       ErrCode = 2 // indicates that a method is not implemented yet
	ErrCode_ErrInternal             ErrCode = 3 // indicates an unknown error (without Code), i.e. in gRPC
	ErrCode_ErrInvalidInput         ErrCode = 100
	ErrCode_ErrBridgeInterrupted    ErrCode = 101
	ErrCode_ErrMissingInput         ErrCode = 102
	ErrCode_ErrSerialization        ErrCode = 103
	ErrCode_ErrDeserialization      ErrCode = 104
	ErrCode_ErrCryptoKeyTypeUnknown ErrCode = 105
	ErrCode_ErrCryptoKeyNotFound    ErrCode = 106
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:   "Undefined",
		1:   "TODO",
		2:   "ErrNotImplemented",
		3:   "ErrInternal",
		100: "ErrInvalidInput",
		101: "ErrBridgeInterrupted",
		102: "ErrMissingInput",
		103: "ErrSerialization",
		104: "ErrDeserialization",
		105: "ErrCryptoKeyTypeUnknown",
		106: "ErrCryptoKeyNotFound",
	}
	ErrCode_value = map[string]int32{
		"Undefined":               0,
		"TODO":                    1,
		"ErrNotImplemented":       2,
		"ErrInternal":             3,
		"ErrInvalidInput":         100,
		"ErrBridgeInterrupted":    101,
		"ErrMissingInput":         102,
		"ErrSerialization":        103,
		"ErrDeserialization":      104,
		"ErrCryptoKeyTypeUnknown": 105,
		"ErrCryptoKeyNotFound":    106,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_gnomobiletypes_proto_enumTypes[1].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_gnomobiletypes_proto_enumTypes[1]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{1}
}

type SetRemote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetRemote) Reset() {
	*x = SetRemote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRemote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRemote) ProtoMessage() {}

func (x *SetRemote) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRemote.ProtoReflect.Descriptor instead.
func (*SetRemote) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{0}
}

type SetChainID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetChainID) Reset() {
	*x = SetChainID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetChainID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetChainID) ProtoMessage() {}

func (x *SetChainID) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetChainID.ProtoReflect.Descriptor instead.
func (*SetChainID) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{1}
}

type SetNameOrBech32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetNameOrBech32) Reset() {
	*x = SetNameOrBech32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNameOrBech32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNameOrBech32) ProtoMessage() {}

func (x *SetNameOrBech32) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNameOrBech32.ProtoReflect.Descriptor instead.
func (*SetNameOrBech32) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{2}
}

type SetPassword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetPassword) Reset() {
	*x = SetPassword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPassword) ProtoMessage() {}

func (x *SetPassword) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPassword.ProtoReflect.Descriptor instead.
func (*SetPassword) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{3}
}

type KeyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    KeyType `protobuf:"varint,1,opt,name=type,proto3,enum=gnomobile.v1.KeyType" json:"type,omitempty"`
	Name    string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PubKey  []byte  `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Address []byte  `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Path    []byte  `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *KeyInfo) Reset() {
	*x = KeyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyInfo) ProtoMessage() {}

func (x *KeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyInfo.ProtoReflect.Descriptor instead.
func (*KeyInfo) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{4}
}

func (x *KeyInfo) GetType() KeyType {
	if x != nil {
		return x.Type
	}
	return KeyType_TypeLocal
}

func (x *KeyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyInfo) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *KeyInfo) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *KeyInfo) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

type ListKeyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListKeyInfo) Reset() {
	*x = ListKeyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeyInfo) ProtoMessage() {}

func (x *ListKeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeyInfo.ProtoReflect.Descriptor instead.
func (*ListKeyInfo) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{5}
}

type CreateAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAccount) Reset() {
	*x = CreateAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccount) ProtoMessage() {}

func (x *CreateAccount) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccount.ProtoReflect.Descriptor instead.
func (*CreateAccount) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{6}
}

type SelectAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SelectAccount) Reset() {
	*x = SelectAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectAccount) ProtoMessage() {}

func (x *SelectAccount) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectAccount.ProtoReflect.Descriptor instead.
func (*SelectAccount) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{7}
}

type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{8}
}

type Call struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Call) Reset() {
	*x = Call{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{9}
}

type ErrDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codes []ErrCode `protobuf:"varint,1,rep,packed,name=codes,proto3,enum=gnomobile.v1.ErrCode" json:"codes,omitempty"`
}

func (x *ErrDetails) Reset() {
	*x = ErrDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrDetails) ProtoMessage() {}

func (x *ErrDetails) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrDetails.ProtoReflect.Descriptor instead.
func (*ErrDetails) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{10}
}

func (x *ErrDetails) GetCodes() []ErrCode {
	if x != nil {
		return x.Codes
	}
	return nil
}

type SetRemote_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remote string `protobuf:"bytes,1,opt,name=remote,proto3" json:"remote,omitempty"`
}

func (x *SetRemote_Request) Reset() {
	*x = SetRemote_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRemote_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRemote_Request) ProtoMessage() {}

func (x *SetRemote_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRemote_Request.ProtoReflect.Descriptor instead.
func (*SetRemote_Request) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SetRemote_Request) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

type SetRemote_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetRemote_Reply) Reset() {
	*x = SetRemote_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRemote_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRemote_Reply) ProtoMessage() {}

func (x *SetRemote_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRemote_Reply.ProtoReflect.Descriptor instead.
func (*SetRemote_Reply) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{0, 1}
}

type SetChainID_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainID string `protobuf:"bytes,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
}

func (x *SetChainID_Request) Reset() {
	*x = SetChainID_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetChainID_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetChainID_Request) ProtoMessage() {}

func (x *SetChainID_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetChainID_Request.ProtoReflect.Descriptor instead.
func (*SetChainID_Request) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SetChainID_Request) GetChainID() string {
	if x != nil {
		return x.ChainID
	}
	return ""
}

type SetChainID_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetChainID_Reply) Reset() {
	*x = SetChainID_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetChainID_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetChainID_Reply) ProtoMessage() {}

func (x *SetChainID_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetChainID_Reply.ProtoReflect.Descriptor instead.
func (*SetChainID_Reply) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{1, 1}
}

type SetNameOrBech32_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameOrBech32 string `protobuf:"bytes,1,opt,name=nameOrBech32,proto3" json:"nameOrBech32,omitempty"`
}

func (x *SetNameOrBech32_Request) Reset() {
	*x = SetNameOrBech32_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNameOrBech32_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNameOrBech32_Request) ProtoMessage() {}

func (x *SetNameOrBech32_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNameOrBech32_Request.ProtoReflect.Descriptor instead.
func (*SetNameOrBech32_Request) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{2, 0}
}

func (x *SetNameOrBech32_Request) GetNameOrBech32() string {
	if x != nil {
		return x.NameOrBech32
	}
	return ""
}

type SetNameOrBech32_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetNameOrBech32_Reply) Reset() {
	*x = SetNameOrBech32_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNameOrBech32_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNameOrBech32_Reply) ProtoMessage() {}

func (x *SetNameOrBech32_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNameOrBech32_Reply.ProtoReflect.Descriptor instead.
func (*SetNameOrBech32_Reply) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{2, 1}
}

type SetPassword_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SetPassword_Request) Reset() {
	*x = SetPassword_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPassword_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPassword_Request) ProtoMessage() {}

func (x *SetPassword_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPassword_Request.ProtoReflect.Descriptor instead.
func (*SetPassword_Request) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SetPassword_Request) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SetPassword_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetPassword_Reply) Reset() {
	*x = SetPassword_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPassword_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPassword_Reply) ProtoMessage() {}

func (x *SetPassword_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPassword_Reply.ProtoReflect.Descriptor instead.
func (*SetPassword_Reply) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{3, 1}
}

type ListKeyInfo_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListKeyInfo_Request) Reset() {
	*x = ListKeyInfo_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKeyInfo_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeyInfo_Request) ProtoMessage() {}

func (x *ListKeyInfo_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeyInfo_Request.ProtoReflect.Descriptor instead.
func (*ListKeyInfo_Request) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{5, 0}
}

type ListKeyInfo_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []*KeyInfo `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *ListKeyInfo_Reply) Reset() {
	*x = ListKeyInfo_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKeyInfo_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeyInfo_Reply) ProtoMessage() {}

func (x *ListKeyInfo_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeyInfo_Reply.ProtoReflect.Descriptor instead.
func (*ListKeyInfo_Reply) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{5, 1}
}

func (x *ListKeyInfo_Reply) GetKeys() []*KeyInfo {
	if x != nil {
		return x.Keys
	}
	return nil
}

type CreateAccount_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameOrBech32 string `protobuf:"bytes,1,opt,name=nameOrBech32,proto3" json:"nameOrBech32,omitempty"`
	Mnemonic     string `protobuf:"bytes,2,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	Bip39Passwd  string `protobuf:"bytes,3,opt,name=bip39Passwd,proto3" json:"bip39Passwd,omitempty"`
	Password     string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Account      uint32 `protobuf:"varint,5,opt,name=account,proto3" json:"account,omitempty"`
	Index        uint32 `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *CreateAccount_Request) Reset() {
	*x = CreateAccount_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccount_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccount_Request) ProtoMessage() {}

func (x *CreateAccount_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccount_Request.ProtoReflect.Descriptor instead.
func (*CreateAccount_Request) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{6, 0}
}

func (x *CreateAccount_Request) GetNameOrBech32() string {
	if x != nil {
		return x.NameOrBech32
	}
	return ""
}

func (x *CreateAccount_Request) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

func (x *CreateAccount_Request) GetBip39Passwd() string {
	if x != nil {
		return x.Bip39Passwd
	}
	return ""
}

func (x *CreateAccount_Request) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAccount_Request) GetAccount() uint32 {
	if x != nil {
		return x.Account
	}
	return 0
}

func (x *CreateAccount_Request) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type CreateAccount_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *KeyInfo `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CreateAccount_Reply) Reset() {
	*x = CreateAccount_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccount_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccount_Reply) ProtoMessage() {}

func (x *CreateAccount_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccount_Reply.ProtoReflect.Descriptor instead.
func (*CreateAccount_Reply) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{6, 1}
}

func (x *CreateAccount_Reply) GetKey() *KeyInfo {
	if x != nil {
		return x.Key
	}
	return nil
}

type SelectAccount_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameOrBech32 string `protobuf:"bytes,1,opt,name=nameOrBech32,proto3" json:"nameOrBech32,omitempty"`
}

func (x *SelectAccount_Request) Reset() {
	*x = SelectAccount_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectAccount_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectAccount_Request) ProtoMessage() {}

func (x *SelectAccount_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectAccount_Request.ProtoReflect.Descriptor instead.
func (*SelectAccount_Request) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{7, 0}
}

func (x *SelectAccount_Request) GetNameOrBech32() string {
	if x != nil {
		return x.NameOrBech32
	}
	return ""
}

type SelectAccount_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *KeyInfo `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SelectAccount_Reply) Reset() {
	*x = SelectAccount_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectAccount_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectAccount_Reply) ProtoMessage() {}

func (x *SelectAccount_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectAccount_Reply.ProtoReflect.Descriptor instead.
func (*SelectAccount_Reply) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{7, 1}
}

func (x *SelectAccount_Reply) GetKey() *KeyInfo {
	if x != nil {
		return x.Key
	}
	return nil
}

type Query_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // Example: "vm/qrender"
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // Example: "gno.land/r/demo/boards\ntestboard"
}

func (x *Query_Request) Reset() {
	*x = Query_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Request) ProtoMessage() {}

func (x *Query_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Request.ProtoReflect.Descriptor instead.
func (*Query_Request) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Query_Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Query_Request) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Query_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Query_Reply) Reset() {
	*x = Query_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Reply) ProtoMessage() {}

func (x *Query_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Reply.ProtoReflect.Descriptor instead.
func (*Query_Reply) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{8, 1}
}

func (x *Query_Reply) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type Call_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackagePath string   `protobuf:"bytes,1,opt,name=packagePath,proto3" json:"packagePath,omitempty"` // Example: "gno.land/r/demo/boards"
	Fnc         string   `protobuf:"bytes,2,opt,name=fnc,proto3" json:"fnc,omitempty"`                 // Example: "CreateReply"
	Args        []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`               // list of arguments specific to the function
	GasFee      string   `protobuf:"bytes,4,opt,name=gasFee,proto3" json:"gasFee,omitempty"`
	GasWanted   int64    `protobuf:"varint,5,opt,name=gasWanted,proto3" json:"gasWanted,omitempty"`
	Password    string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *Call_Request) Reset() {
	*x = Call_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Call_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call_Request) ProtoMessage() {}

func (x *Call_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call_Request.ProtoReflect.Descriptor instead.
func (*Call_Request) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{9, 0}
}

func (x *Call_Request) GetPackagePath() string {
	if x != nil {
		return x.PackagePath
	}
	return ""
}

func (x *Call_Request) GetFnc() string {
	if x != nil {
		return x.Fnc
	}
	return ""
}

func (x *Call_Request) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Call_Request) GetGasFee() string {
	if x != nil {
		return x.GasFee
	}
	return ""
}

func (x *Call_Request) GetGasWanted() int64 {
	if x != nil {
		return x.GasWanted
	}
	return 0
}

func (x *Call_Request) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Call_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Call_Reply) Reset() {
	*x = Call_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnomobiletypes_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Call_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call_Reply) ProtoMessage() {}

func (x *Call_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_gnomobiletypes_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call_Reply.ProtoReflect.Descriptor instead.
func (*Call_Reply) Descriptor() ([]byte, []int) {
	return file_gnomobiletypes_proto_rawDescGZIP(), []int{9, 1}
}

func (x *Call_Reply) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_gnomobiletypes_proto protoreflect.FileDescriptor

var file_gnomobiletypes_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x22, 0x37, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x1a, 0x21, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x3a, 0x0a,
	0x0a, 0x53, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x1a, 0x23, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44,
	0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x49, 0x0a, 0x0f, 0x53, 0x65, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x42, 0x65, 0x63, 0x68, 0x33, 0x32, 0x1a, 0x2d, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x61, 0x6d, 0x65, 0x4f,
	0x72, 0x42, 0x65, 0x63, 0x68, 0x33, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e,
	0x61, 0x6d, 0x65, 0x4f, 0x72, 0x42, 0x65, 0x63, 0x68, 0x33, 0x32, 0x1a, 0x07, 0x0a, 0x05, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x3d, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x1a, 0x25, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x8e, 0x01, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e,
	0x67, 0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x22, 0x4c, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32,
	0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x22, 0xfb, 0x01, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x1a, 0xb7, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x42, 0x65, 0x63, 0x68, 0x33, 0x32,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x42, 0x65,
	0x63, 0x68, 0x33, 0x32, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x63,
	0x12, 0x20, 0x0a, 0x0b, 0x62, 0x69, 0x70, 0x33, 0x39, 0x50, 0x61, 0x73, 0x73, 0x77, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x69, 0x70, 0x33, 0x39, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0x30,
	0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x70, 0x0a, 0x0d, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x1a, 0x2d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c,
	0x6e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x42, 0x65, 0x63, 0x68, 0x33, 0x32, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x42, 0x65, 0x63, 0x68, 0x33, 0x32,
	0x1a, 0x30, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x5b, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x31, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x1f,
	0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0xcd, 0x01, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x1a, 0xa3, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x6e, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x6e, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x61, 0x73, 0x46, 0x65, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61,
	0x73, 0x46, 0x65, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x61, 0x73, 0x57, 0x61, 0x6e, 0x74, 0x65,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x67, 0x61, 0x73, 0x57, 0x61, 0x6e, 0x74,
	0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x1a, 0x1f,
	0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x39, 0x0a, 0x0a, 0x45, 0x72, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x2b, 0x0a,
	0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x67,
	0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x2a, 0x48, 0x0a, 0x07, 0x4b, 0x65,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x10, 0x03, 0x2a, 0xf3, 0x01, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x0d, 0x0a, 0x09, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x54, 0x4f, 0x44, 0x4f, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x72, 0x72,
	0x4e, 0x6f, 0x74, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x10, 0x02,
	0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x10,
	0x03, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x10, 0x64, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x72, 0x72, 0x42, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x75, 0x70, 0x74, 0x65, 0x64, 0x10, 0x65,
	0x12, 0x13, 0x0a, 0x0f, 0x45, 0x72, 0x72, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x10, 0x66, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x72, 0x72, 0x53, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x67, 0x12, 0x16, 0x0a, 0x12, 0x45,
	0x72, 0x72, 0x44, 0x65, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x10, 0x68, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x72, 0x72, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x69,
	0x12, 0x18, 0x0a, 0x14, 0x45, 0x72, 0x72, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x4b, 0x65, 0x79,
	0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x6a, 0x32, 0xe5, 0x05, 0x0a, 0x10, 0x47,
	0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4b, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x67,
	0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x67, 0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4e, 0x0a, 0x0a,
	0x53, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x2e, 0x67, 0x6e, 0x6f,
	0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x49, 0x44, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67,
	0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5d, 0x0a, 0x0f,
	0x53, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x42, 0x65, 0x63, 0x68, 0x33, 0x32, 0x12,
	0x25, 0x2e, 0x67, 0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x42, 0x65, 0x63, 0x68, 0x33, 0x32, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x42,
	0x65, 0x63, 0x68, 0x33, 0x32, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x51, 0x0a, 0x0b, 0x53,
	0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x21, 0x2e, 0x67, 0x6e, 0x6f,
	0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x67, 0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x51,
	0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x2e,
	0x67, 0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x67, 0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x57, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x23, 0x2e, 0x67, 0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x6e, 0x6f, 0x6d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x57, 0x0a, 0x0d, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x2e, 0x67, 0x6e,
	0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x67, 0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x3f, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1b, 0x2e, 0x67,
	0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x6e, 0x6f, 0x6d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x1a, 0x2e, 0x67,
	0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x6e, 0x6f, 0x6d, 0x6f,
	0x62, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x2e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x4f, 0x0a, 0x12, 0x6c, 0x61, 0x6e, 0x64, 0x2e, 0x67, 0x6e, 0x6f, 0x2e, 0x67,
	0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6e, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x6e, 0x6f,
	0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67,
	0x6e, 0x6f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0xa2, 0x02, 0x03,
	0x52, 0x54, 0x47, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gnomobiletypes_proto_rawDescOnce sync.Once
	file_gnomobiletypes_proto_rawDescData = file_gnomobiletypes_proto_rawDesc
)

func file_gnomobiletypes_proto_rawDescGZIP() []byte {
	file_gnomobiletypes_proto_rawDescOnce.Do(func() {
		file_gnomobiletypes_proto_rawDescData = protoimpl.X.CompressGZIP(file_gnomobiletypes_proto_rawDescData)
	})
	return file_gnomobiletypes_proto_rawDescData
}

var file_gnomobiletypes_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gnomobiletypes_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_gnomobiletypes_proto_goTypes = []interface{}{
	(KeyType)(0),                    // 0: gnomobile.v1.KeyType
	(ErrCode)(0),                    // 1: gnomobile.v1.ErrCode
	(*SetRemote)(nil),               // 2: gnomobile.v1.SetRemote
	(*SetChainID)(nil),              // 3: gnomobile.v1.SetChainID
	(*SetNameOrBech32)(nil),         // 4: gnomobile.v1.SetNameOrBech32
	(*SetPassword)(nil),             // 5: gnomobile.v1.SetPassword
	(*KeyInfo)(nil),                 // 6: gnomobile.v1.KeyInfo
	(*ListKeyInfo)(nil),             // 7: gnomobile.v1.ListKeyInfo
	(*CreateAccount)(nil),           // 8: gnomobile.v1.CreateAccount
	(*SelectAccount)(nil),           // 9: gnomobile.v1.SelectAccount
	(*Query)(nil),                   // 10: gnomobile.v1.Query
	(*Call)(nil),                    // 11: gnomobile.v1.Call
	(*ErrDetails)(nil),              // 12: gnomobile.v1.ErrDetails
	(*SetRemote_Request)(nil),       // 13: gnomobile.v1.SetRemote.Request
	(*SetRemote_Reply)(nil),         // 14: gnomobile.v1.SetRemote.Reply
	(*SetChainID_Request)(nil),      // 15: gnomobile.v1.SetChainID.Request
	(*SetChainID_Reply)(nil),        // 16: gnomobile.v1.SetChainID.Reply
	(*SetNameOrBech32_Request)(nil), // 17: gnomobile.v1.SetNameOrBech32.Request
	(*SetNameOrBech32_Reply)(nil),   // 18: gnomobile.v1.SetNameOrBech32.Reply
	(*SetPassword_Request)(nil),     // 19: gnomobile.v1.SetPassword.Request
	(*SetPassword_Reply)(nil),       // 20: gnomobile.v1.SetPassword.Reply
	(*ListKeyInfo_Request)(nil),     // 21: gnomobile.v1.ListKeyInfo.Request
	(*ListKeyInfo_Reply)(nil),       // 22: gnomobile.v1.ListKeyInfo.Reply
	(*CreateAccount_Request)(nil),   // 23: gnomobile.v1.CreateAccount.Request
	(*CreateAccount_Reply)(nil),     // 24: gnomobile.v1.CreateAccount.Reply
	(*SelectAccount_Request)(nil),   // 25: gnomobile.v1.SelectAccount.Request
	(*SelectAccount_Reply)(nil),     // 26: gnomobile.v1.SelectAccount.Reply
	(*Query_Request)(nil),           // 27: gnomobile.v1.Query.Request
	(*Query_Reply)(nil),             // 28: gnomobile.v1.Query.Reply
	(*Call_Request)(nil),            // 29: gnomobile.v1.Call.Request
	(*Call_Reply)(nil),              // 30: gnomobile.v1.Call.Reply
}
var file_gnomobiletypes_proto_depIdxs = []int32{
	0,  // 0: gnomobile.v1.KeyInfo.type:type_name -> gnomobile.v1.KeyType
	1,  // 1: gnomobile.v1.ErrDetails.codes:type_name -> gnomobile.v1.ErrCode
	6,  // 2: gnomobile.v1.ListKeyInfo.Reply.keys:type_name -> gnomobile.v1.KeyInfo
	6,  // 3: gnomobile.v1.CreateAccount.Reply.key:type_name -> gnomobile.v1.KeyInfo
	6,  // 4: gnomobile.v1.SelectAccount.Reply.key:type_name -> gnomobile.v1.KeyInfo
	13, // 5: gnomobile.v1.GnomobileService.SetRemote:input_type -> gnomobile.v1.SetRemote.Request
	15, // 6: gnomobile.v1.GnomobileService.SetChainID:input_type -> gnomobile.v1.SetChainID.Request
	17, // 7: gnomobile.v1.GnomobileService.SetNameOrBech32:input_type -> gnomobile.v1.SetNameOrBech32.Request
	19, // 8: gnomobile.v1.GnomobileService.SetPassword:input_type -> gnomobile.v1.SetPassword.Request
	21, // 9: gnomobile.v1.GnomobileService.ListKeyInfo:input_type -> gnomobile.v1.ListKeyInfo.Request
	23, // 10: gnomobile.v1.GnomobileService.CreateAccount:input_type -> gnomobile.v1.CreateAccount.Request
	25, // 11: gnomobile.v1.GnomobileService.SelectAccount:input_type -> gnomobile.v1.SelectAccount.Request
	27, // 12: gnomobile.v1.GnomobileService.Query:input_type -> gnomobile.v1.Query.Request
	29, // 13: gnomobile.v1.GnomobileService.Call:input_type -> gnomobile.v1.Call.Request
	14, // 14: gnomobile.v1.GnomobileService.SetRemote:output_type -> gnomobile.v1.SetRemote.Reply
	16, // 15: gnomobile.v1.GnomobileService.SetChainID:output_type -> gnomobile.v1.SetChainID.Reply
	18, // 16: gnomobile.v1.GnomobileService.SetNameOrBech32:output_type -> gnomobile.v1.SetNameOrBech32.Reply
	20, // 17: gnomobile.v1.GnomobileService.SetPassword:output_type -> gnomobile.v1.SetPassword.Reply
	22, // 18: gnomobile.v1.GnomobileService.ListKeyInfo:output_type -> gnomobile.v1.ListKeyInfo.Reply
	24, // 19: gnomobile.v1.GnomobileService.CreateAccount:output_type -> gnomobile.v1.CreateAccount.Reply
	26, // 20: gnomobile.v1.GnomobileService.SelectAccount:output_type -> gnomobile.v1.SelectAccount.Reply
	28, // 21: gnomobile.v1.GnomobileService.Query:output_type -> gnomobile.v1.Query.Reply
	30, // 22: gnomobile.v1.GnomobileService.Call:output_type -> gnomobile.v1.Call.Reply
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_gnomobiletypes_proto_init() }
func file_gnomobiletypes_proto_init() {
	if File_gnomobiletypes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gnomobiletypes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRemote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetChainID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNameOrBech32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPassword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKeyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Call); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRemote_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRemote_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetChainID_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetChainID_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNameOrBech32_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNameOrBech32_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPassword_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPassword_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKeyInfo_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKeyInfo_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccount_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccount_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectAccount_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectAccount_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Call_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnomobiletypes_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Call_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gnomobiletypes_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gnomobiletypes_proto_goTypes,
		DependencyIndexes: file_gnomobiletypes_proto_depIdxs,
		EnumInfos:         file_gnomobiletypes_proto_enumTypes,
		MessageInfos:      file_gnomobiletypes_proto_msgTypes,
	}.Build()
	File_gnomobiletypes_proto = out.File
	file_gnomobiletypes_proto_rawDesc = nil
	file_gnomobiletypes_proto_goTypes = nil
	file_gnomobiletypes_proto_depIdxs = nil
}
