//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: gnomobiletypes.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// GnomobileService is the service to interact with the Gno blockchain
///
/// Usage: instantiate `Gnomobile_V1_GnomobileServiceClient`, then call methods of this protocol to make API calls.
internal protocol Gnomobile_V1_GnomobileServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Gnomobile_V1_GnomobileServiceClientInterceptorFactoryProtocol? { get }

  func setRemote(
    _ request: Gnomobile_V1_SetRemote.Request,
    callOptions: CallOptions?
  ) -> UnaryCall<Gnomobile_V1_SetRemote.Request, Gnomobile_V1_SetRemote.Reply>

  func setChainID(
    _ request: Gnomobile_V1_SetChainID.Request,
    callOptions: CallOptions?
  ) -> UnaryCall<Gnomobile_V1_SetChainID.Request, Gnomobile_V1_SetChainID.Reply>

  func setNameOrBech32(
    _ request: Gnomobile_V1_SetNameOrBech32.Request,
    callOptions: CallOptions?
  ) -> UnaryCall<Gnomobile_V1_SetNameOrBech32.Request, Gnomobile_V1_SetNameOrBech32.Reply>

  func setPassword(
    _ request: Gnomobile_V1_SetPassword.Request,
    callOptions: CallOptions?
  ) -> UnaryCall<Gnomobile_V1_SetPassword.Request, Gnomobile_V1_SetPassword.Reply>

  func listKeyInfo(
    _ request: Gnomobile_V1_ListKeyInfo.Request,
    callOptions: CallOptions?
  ) -> UnaryCall<Gnomobile_V1_ListKeyInfo.Request, Gnomobile_V1_ListKeyInfo.Reply>

  func createAccount(
    _ request: Gnomobile_V1_CreateAccount.Request,
    callOptions: CallOptions?
  ) -> UnaryCall<Gnomobile_V1_CreateAccount.Request, Gnomobile_V1_CreateAccount.Reply>

  func selectAccount(
    _ request: Gnomobile_V1_SelectAccount.Request,
    callOptions: CallOptions?
  ) -> UnaryCall<Gnomobile_V1_SelectAccount.Request, Gnomobile_V1_SelectAccount.Reply>

  func query(
    _ request: Gnomobile_V1_Query.Request,
    callOptions: CallOptions?
  ) -> UnaryCall<Gnomobile_V1_Query.Request, Gnomobile_V1_Query.Reply>

  func call(
    _ request: Gnomobile_V1_Call.Request,
    callOptions: CallOptions?
  ) -> UnaryCall<Gnomobile_V1_Call.Request, Gnomobile_V1_Call.Reply>
}

extension Gnomobile_V1_GnomobileServiceClientProtocol {
  internal var serviceName: String {
    return "gnomobile.v1.GnomobileService"
  }

  /// Set the connection addresse for the remote node. If you don't call this, the default is
  /// "127.0.0.1:26657"
  ///
  /// - Parameters:
  ///   - request: Request to send to SetRemote.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func setRemote(
    _ request: Gnomobile_V1_SetRemote.Request,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Gnomobile_V1_SetRemote.Request, Gnomobile_V1_SetRemote.Reply> {
    return self.makeUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setRemote.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetRemoteInterceptors() ?? []
    )
  }

  /// Set the chain ID for the remote node. If you don't call this, the default is "dev"
  ///
  /// - Parameters:
  ///   - request: Request to send to SetChainID.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func setChainID(
    _ request: Gnomobile_V1_SetChainID.Request,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Gnomobile_V1_SetChainID.Request, Gnomobile_V1_SetChainID.Reply> {
    return self.makeUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setChainID.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetChainIDInterceptors() ?? []
    )
  }

  /// Set the nameOrBech32 for the account in the keybase, used for later operations
  ///
  /// - Parameters:
  ///   - request: Request to send to SetNameOrBech32.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func setNameOrBech32(
    _ request: Gnomobile_V1_SetNameOrBech32.Request,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Gnomobile_V1_SetNameOrBech32.Request, Gnomobile_V1_SetNameOrBech32.Reply> {
    return self.makeUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setNameOrBech32.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetNameOrBech32Interceptors() ?? []
    )
  }

  /// Set the password for the account in the keybase, used for later operations
  ///
  /// - Parameters:
  ///   - request: Request to send to SetPassword.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func setPassword(
    _ request: Gnomobile_V1_SetPassword.Request,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Gnomobile_V1_SetPassword.Request, Gnomobile_V1_SetPassword.Reply> {
    return self.makeUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setPassword.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetPasswordInterceptors() ?? []
    )
  }

  /// Get the keys informations in the keybase
  ///
  /// - Parameters:
  ///   - request: Request to send to ListKeyInfo.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func listKeyInfo(
    _ request: Gnomobile_V1_ListKeyInfo.Request,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Gnomobile_V1_ListKeyInfo.Request, Gnomobile_V1_ListKeyInfo.Reply> {
    return self.makeUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.listKeyInfo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListKeyInfoInterceptors() ?? []
    )
  }

  /// Create a new account the keybase using the name an password specified by SetAccount
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateAccount.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createAccount(
    _ request: Gnomobile_V1_CreateAccount.Request,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Gnomobile_V1_CreateAccount.Request, Gnomobile_V1_CreateAccount.Reply> {
    return self.makeUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.createAccount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateAccountInterceptors() ?? []
    )
  }

  /// SelectAccount selects the account to use for later operations
  ///
  /// - Parameters:
  ///   - request: Request to send to SelectAccount.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func selectAccount(
    _ request: Gnomobile_V1_SelectAccount.Request,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Gnomobile_V1_SelectAccount.Request, Gnomobile_V1_SelectAccount.Reply> {
    return self.makeUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.selectAccount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSelectAccountInterceptors() ?? []
    )
  }

  /// Make an ABCI query to the remote node.
  ///
  /// - Parameters:
  ///   - request: Request to send to Query.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func query(
    _ request: Gnomobile_V1_Query.Request,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Gnomobile_V1_Query.Request, Gnomobile_V1_Query.Reply> {
    return self.makeUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.query.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryInterceptors() ?? []
    )
  }

  /// Call a specific realm function.
  ///
  /// - Parameters:
  ///   - request: Request to send to Call.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func call(
    _ request: Gnomobile_V1_Call.Request,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Gnomobile_V1_Call.Request, Gnomobile_V1_Call.Reply> {
    return self.makeUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.call.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCallInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Gnomobile_V1_GnomobileServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Gnomobile_V1_GnomobileServiceNIOClient")
internal final class Gnomobile_V1_GnomobileServiceClient: Gnomobile_V1_GnomobileServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Gnomobile_V1_GnomobileServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Gnomobile_V1_GnomobileServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the gnomobile.v1.GnomobileService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Gnomobile_V1_GnomobileServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Gnomobile_V1_GnomobileServiceNIOClient: Gnomobile_V1_GnomobileServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Gnomobile_V1_GnomobileServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the gnomobile.v1.GnomobileService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Gnomobile_V1_GnomobileServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// GnomobileService is the service to interact with the Gno blockchain
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Gnomobile_V1_GnomobileServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Gnomobile_V1_GnomobileServiceClientInterceptorFactoryProtocol? { get }

  func makeSetRemoteCall(
    _ request: Gnomobile_V1_SetRemote.Request,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_SetRemote.Request, Gnomobile_V1_SetRemote.Reply>

  func makeSetChainIDCall(
    _ request: Gnomobile_V1_SetChainID.Request,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_SetChainID.Request, Gnomobile_V1_SetChainID.Reply>

  func makeSetNameOrBech32Call(
    _ request: Gnomobile_V1_SetNameOrBech32.Request,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_SetNameOrBech32.Request, Gnomobile_V1_SetNameOrBech32.Reply>

  func makeSetPasswordCall(
    _ request: Gnomobile_V1_SetPassword.Request,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_SetPassword.Request, Gnomobile_V1_SetPassword.Reply>

  func makeListKeyInfoCall(
    _ request: Gnomobile_V1_ListKeyInfo.Request,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_ListKeyInfo.Request, Gnomobile_V1_ListKeyInfo.Reply>

  func makeCreateAccountCall(
    _ request: Gnomobile_V1_CreateAccount.Request,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_CreateAccount.Request, Gnomobile_V1_CreateAccount.Reply>

  func makeSelectAccountCall(
    _ request: Gnomobile_V1_SelectAccount.Request,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_SelectAccount.Request, Gnomobile_V1_SelectAccount.Reply>

  func makeQueryCall(
    _ request: Gnomobile_V1_Query.Request,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_Query.Request, Gnomobile_V1_Query.Reply>

  func makeCallCall(
    _ request: Gnomobile_V1_Call.Request,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_Call.Request, Gnomobile_V1_Call.Reply>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Gnomobile_V1_GnomobileServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Gnomobile_V1_GnomobileServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Gnomobile_V1_GnomobileServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeSetRemoteCall(
    _ request: Gnomobile_V1_SetRemote.Request,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_SetRemote.Request, Gnomobile_V1_SetRemote.Reply> {
    return self.makeAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setRemote.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetRemoteInterceptors() ?? []
    )
  }

  internal func makeSetChainIDCall(
    _ request: Gnomobile_V1_SetChainID.Request,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_SetChainID.Request, Gnomobile_V1_SetChainID.Reply> {
    return self.makeAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setChainID.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetChainIDInterceptors() ?? []
    )
  }

  internal func makeSetNameOrBech32Call(
    _ request: Gnomobile_V1_SetNameOrBech32.Request,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_SetNameOrBech32.Request, Gnomobile_V1_SetNameOrBech32.Reply> {
    return self.makeAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setNameOrBech32.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetNameOrBech32Interceptors() ?? []
    )
  }

  internal func makeSetPasswordCall(
    _ request: Gnomobile_V1_SetPassword.Request,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_SetPassword.Request, Gnomobile_V1_SetPassword.Reply> {
    return self.makeAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setPassword.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetPasswordInterceptors() ?? []
    )
  }

  internal func makeListKeyInfoCall(
    _ request: Gnomobile_V1_ListKeyInfo.Request,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_ListKeyInfo.Request, Gnomobile_V1_ListKeyInfo.Reply> {
    return self.makeAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.listKeyInfo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListKeyInfoInterceptors() ?? []
    )
  }

  internal func makeCreateAccountCall(
    _ request: Gnomobile_V1_CreateAccount.Request,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_CreateAccount.Request, Gnomobile_V1_CreateAccount.Reply> {
    return self.makeAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.createAccount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateAccountInterceptors() ?? []
    )
  }

  internal func makeSelectAccountCall(
    _ request: Gnomobile_V1_SelectAccount.Request,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_SelectAccount.Request, Gnomobile_V1_SelectAccount.Reply> {
    return self.makeAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.selectAccount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSelectAccountInterceptors() ?? []
    )
  }

  internal func makeQueryCall(
    _ request: Gnomobile_V1_Query.Request,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_Query.Request, Gnomobile_V1_Query.Reply> {
    return self.makeAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.query.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryInterceptors() ?? []
    )
  }

  internal func makeCallCall(
    _ request: Gnomobile_V1_Call.Request,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Gnomobile_V1_Call.Request, Gnomobile_V1_Call.Reply> {
    return self.makeAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.call.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCallInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Gnomobile_V1_GnomobileServiceAsyncClientProtocol {
  internal func setRemote(
    _ request: Gnomobile_V1_SetRemote.Request,
    callOptions: CallOptions? = nil
  ) async throws -> Gnomobile_V1_SetRemote.Reply {
    return try await self.performAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setRemote.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetRemoteInterceptors() ?? []
    )
  }

  internal func setChainID(
    _ request: Gnomobile_V1_SetChainID.Request,
    callOptions: CallOptions? = nil
  ) async throws -> Gnomobile_V1_SetChainID.Reply {
    return try await self.performAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setChainID.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetChainIDInterceptors() ?? []
    )
  }

  internal func setNameOrBech32(
    _ request: Gnomobile_V1_SetNameOrBech32.Request,
    callOptions: CallOptions? = nil
  ) async throws -> Gnomobile_V1_SetNameOrBech32.Reply {
    return try await self.performAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setNameOrBech32.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetNameOrBech32Interceptors() ?? []
    )
  }

  internal func setPassword(
    _ request: Gnomobile_V1_SetPassword.Request,
    callOptions: CallOptions? = nil
  ) async throws -> Gnomobile_V1_SetPassword.Reply {
    return try await self.performAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setPassword.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetPasswordInterceptors() ?? []
    )
  }

  internal func listKeyInfo(
    _ request: Gnomobile_V1_ListKeyInfo.Request,
    callOptions: CallOptions? = nil
  ) async throws -> Gnomobile_V1_ListKeyInfo.Reply {
    return try await self.performAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.listKeyInfo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListKeyInfoInterceptors() ?? []
    )
  }

  internal func createAccount(
    _ request: Gnomobile_V1_CreateAccount.Request,
    callOptions: CallOptions? = nil
  ) async throws -> Gnomobile_V1_CreateAccount.Reply {
    return try await self.performAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.createAccount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateAccountInterceptors() ?? []
    )
  }

  internal func selectAccount(
    _ request: Gnomobile_V1_SelectAccount.Request,
    callOptions: CallOptions? = nil
  ) async throws -> Gnomobile_V1_SelectAccount.Reply {
    return try await self.performAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.selectAccount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSelectAccountInterceptors() ?? []
    )
  }

  internal func query(
    _ request: Gnomobile_V1_Query.Request,
    callOptions: CallOptions? = nil
  ) async throws -> Gnomobile_V1_Query.Reply {
    return try await self.performAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.query.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryInterceptors() ?? []
    )
  }

  internal func call(
    _ request: Gnomobile_V1_Call.Request,
    callOptions: CallOptions? = nil
  ) async throws -> Gnomobile_V1_Call.Reply {
    return try await self.performAsyncUnaryCall(
      path: Gnomobile_V1_GnomobileServiceClientMetadata.Methods.call.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCallInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Gnomobile_V1_GnomobileServiceAsyncClient: Gnomobile_V1_GnomobileServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Gnomobile_V1_GnomobileServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Gnomobile_V1_GnomobileServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Gnomobile_V1_GnomobileServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'setRemote'.
  func makeSetRemoteInterceptors() -> [ClientInterceptor<Gnomobile_V1_SetRemote.Request, Gnomobile_V1_SetRemote.Reply>]

  /// - Returns: Interceptors to use when invoking 'setChainID'.
  func makeSetChainIDInterceptors() -> [ClientInterceptor<Gnomobile_V1_SetChainID.Request, Gnomobile_V1_SetChainID.Reply>]

  /// - Returns: Interceptors to use when invoking 'setNameOrBech32'.
  func makeSetNameOrBech32Interceptors() -> [ClientInterceptor<Gnomobile_V1_SetNameOrBech32.Request, Gnomobile_V1_SetNameOrBech32.Reply>]

  /// - Returns: Interceptors to use when invoking 'setPassword'.
  func makeSetPasswordInterceptors() -> [ClientInterceptor<Gnomobile_V1_SetPassword.Request, Gnomobile_V1_SetPassword.Reply>]

  /// - Returns: Interceptors to use when invoking 'listKeyInfo'.
  func makeListKeyInfoInterceptors() -> [ClientInterceptor<Gnomobile_V1_ListKeyInfo.Request, Gnomobile_V1_ListKeyInfo.Reply>]

  /// - Returns: Interceptors to use when invoking 'createAccount'.
  func makeCreateAccountInterceptors() -> [ClientInterceptor<Gnomobile_V1_CreateAccount.Request, Gnomobile_V1_CreateAccount.Reply>]

  /// - Returns: Interceptors to use when invoking 'selectAccount'.
  func makeSelectAccountInterceptors() -> [ClientInterceptor<Gnomobile_V1_SelectAccount.Request, Gnomobile_V1_SelectAccount.Reply>]

  /// - Returns: Interceptors to use when invoking 'query'.
  func makeQueryInterceptors() -> [ClientInterceptor<Gnomobile_V1_Query.Request, Gnomobile_V1_Query.Reply>]

  /// - Returns: Interceptors to use when invoking 'call'.
  func makeCallInterceptors() -> [ClientInterceptor<Gnomobile_V1_Call.Request, Gnomobile_V1_Call.Reply>]
}

internal enum Gnomobile_V1_GnomobileServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "GnomobileService",
    fullName: "gnomobile.v1.GnomobileService",
    methods: [
      Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setRemote,
      Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setChainID,
      Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setNameOrBech32,
      Gnomobile_V1_GnomobileServiceClientMetadata.Methods.setPassword,
      Gnomobile_V1_GnomobileServiceClientMetadata.Methods.listKeyInfo,
      Gnomobile_V1_GnomobileServiceClientMetadata.Methods.createAccount,
      Gnomobile_V1_GnomobileServiceClientMetadata.Methods.selectAccount,
      Gnomobile_V1_GnomobileServiceClientMetadata.Methods.query,
      Gnomobile_V1_GnomobileServiceClientMetadata.Methods.call,
    ]
  )

  internal enum Methods {
    internal static let setRemote = GRPCMethodDescriptor(
      name: "SetRemote",
      path: "/gnomobile.v1.GnomobileService/SetRemote",
      type: GRPCCallType.unary
    )

    internal static let setChainID = GRPCMethodDescriptor(
      name: "SetChainID",
      path: "/gnomobile.v1.GnomobileService/SetChainID",
      type: GRPCCallType.unary
    )

    internal static let setNameOrBech32 = GRPCMethodDescriptor(
      name: "SetNameOrBech32",
      path: "/gnomobile.v1.GnomobileService/SetNameOrBech32",
      type: GRPCCallType.unary
    )

    internal static let setPassword = GRPCMethodDescriptor(
      name: "SetPassword",
      path: "/gnomobile.v1.GnomobileService/SetPassword",
      type: GRPCCallType.unary
    )

    internal static let listKeyInfo = GRPCMethodDescriptor(
      name: "ListKeyInfo",
      path: "/gnomobile.v1.GnomobileService/ListKeyInfo",
      type: GRPCCallType.unary
    )

    internal static let createAccount = GRPCMethodDescriptor(
      name: "CreateAccount",
      path: "/gnomobile.v1.GnomobileService/CreateAccount",
      type: GRPCCallType.unary
    )

    internal static let selectAccount = GRPCMethodDescriptor(
      name: "SelectAccount",
      path: "/gnomobile.v1.GnomobileService/SelectAccount",
      type: GRPCCallType.unary
    )

    internal static let query = GRPCMethodDescriptor(
      name: "Query",
      path: "/gnomobile.v1.GnomobileService/Query",
      type: GRPCCallType.unary
    )

    internal static let call = GRPCMethodDescriptor(
      name: "Call",
      path: "/gnomobile.v1.GnomobileService/Call",
      type: GRPCCallType.unary
    )
  }
}

