// @generated by protoc-gen-es v1.3.1
// @generated from file gnomobiletypes.proto (package land.gno.gnomobile.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * messages
 *
 * @generated from message land.gno.gnomobile.v1.SetRemote_Request
 */
export declare class SetRemote_Request extends Message<SetRemote_Request> {
  /**
   * @generated from field: string Remote = 1;
   */
  Remote: string;

  constructor(data?: PartialMessage<SetRemote_Request>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.SetRemote_Request";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetRemote_Request;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetRemote_Request;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetRemote_Request;

  static equals(a: SetRemote_Request | PlainMessage<SetRemote_Request> | undefined, b: SetRemote_Request | PlainMessage<SetRemote_Request> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.SetRemote_Reply
 */
export declare class SetRemote_Reply extends Message<SetRemote_Reply> {
  constructor(data?: PartialMessage<SetRemote_Reply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.SetRemote_Reply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetRemote_Reply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetRemote_Reply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetRemote_Reply;

  static equals(a: SetRemote_Reply | PlainMessage<SetRemote_Reply> | undefined, b: SetRemote_Reply | PlainMessage<SetRemote_Reply> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.SetChainID_Request
 */
export declare class SetChainID_Request extends Message<SetChainID_Request> {
  /**
   * @generated from field: string ChainID = 1;
   */
  ChainID: string;

  constructor(data?: PartialMessage<SetChainID_Request>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.SetChainID_Request";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetChainID_Request;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetChainID_Request;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetChainID_Request;

  static equals(a: SetChainID_Request | PlainMessage<SetChainID_Request> | undefined, b: SetChainID_Request | PlainMessage<SetChainID_Request> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.SetChainID_Reply
 */
export declare class SetChainID_Reply extends Message<SetChainID_Reply> {
  constructor(data?: PartialMessage<SetChainID_Reply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.SetChainID_Reply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetChainID_Reply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetChainID_Reply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetChainID_Reply;

  static equals(a: SetChainID_Reply | PlainMessage<SetChainID_Reply> | undefined, b: SetChainID_Reply | PlainMessage<SetChainID_Reply> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.SetNameOrBech32_Request
 */
export declare class SetNameOrBech32_Request extends Message<SetNameOrBech32_Request> {
  /**
   * @generated from field: string NameOrBech32 = 1;
   */
  NameOrBech32: string;

  constructor(data?: PartialMessage<SetNameOrBech32_Request>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.SetNameOrBech32_Request";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetNameOrBech32_Request;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetNameOrBech32_Request;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetNameOrBech32_Request;

  static equals(a: SetNameOrBech32_Request | PlainMessage<SetNameOrBech32_Request> | undefined, b: SetNameOrBech32_Request | PlainMessage<SetNameOrBech32_Request> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.SetNameOrBech32_Reply
 */
export declare class SetNameOrBech32_Reply extends Message<SetNameOrBech32_Reply> {
  constructor(data?: PartialMessage<SetNameOrBech32_Reply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.SetNameOrBech32_Reply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetNameOrBech32_Reply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetNameOrBech32_Reply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetNameOrBech32_Reply;

  static equals(a: SetNameOrBech32_Reply | PlainMessage<SetNameOrBech32_Reply> | undefined, b: SetNameOrBech32_Reply | PlainMessage<SetNameOrBech32_Reply> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.SetPassword_Request
 */
export declare class SetPassword_Request extends Message<SetPassword_Request> {
  /**
   * @generated from field: string Password = 1;
   */
  Password: string;

  constructor(data?: PartialMessage<SetPassword_Request>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.SetPassword_Request";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetPassword_Request;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetPassword_Request;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetPassword_Request;

  static equals(a: SetPassword_Request | PlainMessage<SetPassword_Request> | undefined, b: SetPassword_Request | PlainMessage<SetPassword_Request> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.SetPassword_Reply
 */
export declare class SetPassword_Reply extends Message<SetPassword_Reply> {
  constructor(data?: PartialMessage<SetPassword_Reply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.SetPassword_Reply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetPassword_Reply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetPassword_Reply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetPassword_Reply;

  static equals(a: SetPassword_Reply | PlainMessage<SetPassword_Reply> | undefined, b: SetPassword_Reply | PlainMessage<SetPassword_Reply> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.GenerateRecoveryPhrase_Request
 */
export declare class GenerateRecoveryPhrase_Request extends Message<GenerateRecoveryPhrase_Request> {
  constructor(data?: PartialMessage<GenerateRecoveryPhrase_Request>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.GenerateRecoveryPhrase_Request";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenerateRecoveryPhrase_Request;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenerateRecoveryPhrase_Request;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenerateRecoveryPhrase_Request;

  static equals(a: GenerateRecoveryPhrase_Request | PlainMessage<GenerateRecoveryPhrase_Request> | undefined, b: GenerateRecoveryPhrase_Request | PlainMessage<GenerateRecoveryPhrase_Request> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.GenerateRecoveryPhrase_Reply
 */
export declare class GenerateRecoveryPhrase_Reply extends Message<GenerateRecoveryPhrase_Reply> {
  /**
   * @generated from field: string Phrase = 1;
   */
  Phrase: string;

  constructor(data?: PartialMessage<GenerateRecoveryPhrase_Reply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.GenerateRecoveryPhrase_Reply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenerateRecoveryPhrase_Reply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenerateRecoveryPhrase_Reply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenerateRecoveryPhrase_Reply;

  static equals(a: GenerateRecoveryPhrase_Reply | PlainMessage<GenerateRecoveryPhrase_Reply> | undefined, b: GenerateRecoveryPhrase_Reply | PlainMessage<GenerateRecoveryPhrase_Reply> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.Query_Request
 */
export declare class Query_Request extends Message<Query_Request> {
  /**
   * @generated from field: string Path = 1;
   */
  Path: string;

  /**
   * @generated from field: bytes Data = 2;
   */
  Data: Uint8Array;

  constructor(data?: PartialMessage<Query_Request>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.Query_Request";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Query_Request;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Query_Request;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Query_Request;

  static equals(a: Query_Request | PlainMessage<Query_Request> | undefined, b: Query_Request | PlainMessage<Query_Request> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.Query_Reply
 */
export declare class Query_Reply extends Message<Query_Reply> {
  /**
   * @generated from field: bytes Result = 1;
   */
  Result: Uint8Array;

  constructor(data?: PartialMessage<Query_Reply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.Query_Reply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Query_Reply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Query_Reply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Query_Reply;

  static equals(a: Query_Reply | PlainMessage<Query_Reply> | undefined, b: Query_Reply | PlainMessage<Query_Reply> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.Call_Request
 */
export declare class Call_Request extends Message<Call_Request> {
  /**
   * @generated from field: string PackagePath = 1;
   */
  PackagePath: string;

  /**
   * @generated from field: string Fnc = 2;
   */
  Fnc: string;

  /**
   * @generated from field: repeated string Args = 3;
   */
  Args: string[];

  /**
   * @generated from field: string GasFee = 4;
   */
  GasFee: string;

  /**
   * @generated from field: sint64 GasWanted = 5;
   */
  GasWanted: bigint;

  /**
   * @generated from field: string Send = 6;
   */
  Send: string;

  /**
   * @generated from field: string Memo = 7;
   */
  Memo: string;

  constructor(data?: PartialMessage<Call_Request>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.Call_Request";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Call_Request;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Call_Request;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Call_Request;

  static equals(a: Call_Request | PlainMessage<Call_Request> | undefined, b: Call_Request | PlainMessage<Call_Request> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.Call_Reply
 */
export declare class Call_Reply extends Message<Call_Reply> {
  /**
   * @generated from field: bytes Result = 1;
   */
  Result: Uint8Array;

  constructor(data?: PartialMessage<Call_Reply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.Call_Reply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Call_Reply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Call_Reply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Call_Reply;

  static equals(a: Call_Reply | PlainMessage<Call_Reply> | undefined, b: Call_Reply | PlainMessage<Call_Reply> | undefined): boolean;
}

