// @generated by protoc-gen-es v1.3.1
// @generated from file gnomobiletypes.proto (package land.gno.gnomobile.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * messages
 *
 * @generated from message land.gno.gnomobile.v1.SetRemote_Request
 */
export const SetRemote_Request = proto3.makeMessageType(
  "land.gno.gnomobile.v1.SetRemote_Request",
  () => [
    { no: 1, name: "Remote", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message land.gno.gnomobile.v1.SetRemote_Reply
 */
export const SetRemote_Reply = proto3.makeMessageType(
  "land.gno.gnomobile.v1.SetRemote_Reply",
  [],
);

/**
 * @generated from message land.gno.gnomobile.v1.SetChainID_Request
 */
export const SetChainID_Request = proto3.makeMessageType(
  "land.gno.gnomobile.v1.SetChainID_Request",
  () => [
    { no: 1, name: "ChainID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message land.gno.gnomobile.v1.SetChainID_Reply
 */
export const SetChainID_Reply = proto3.makeMessageType(
  "land.gno.gnomobile.v1.SetChainID_Reply",
  [],
);

/**
 * @generated from message land.gno.gnomobile.v1.SetNameOrBech32_Request
 */
export const SetNameOrBech32_Request = proto3.makeMessageType(
  "land.gno.gnomobile.v1.SetNameOrBech32_Request",
  () => [
    { no: 1, name: "NameOrBech32", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message land.gno.gnomobile.v1.SetNameOrBech32_Reply
 */
export const SetNameOrBech32_Reply = proto3.makeMessageType(
  "land.gno.gnomobile.v1.SetNameOrBech32_Reply",
  [],
);

/**
 * @generated from message land.gno.gnomobile.v1.SetPassword_Request
 */
export const SetPassword_Request = proto3.makeMessageType(
  "land.gno.gnomobile.v1.SetPassword_Request",
  () => [
    { no: 1, name: "Password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message land.gno.gnomobile.v1.SetPassword_Reply
 */
export const SetPassword_Reply = proto3.makeMessageType(
  "land.gno.gnomobile.v1.SetPassword_Reply",
  [],
);

/**
 * @generated from message land.gno.gnomobile.v1.GenerateRecoveryPhrase_Request
 */
export const GenerateRecoveryPhrase_Request = proto3.makeMessageType(
  "land.gno.gnomobile.v1.GenerateRecoveryPhrase_Request",
  [],
);

/**
 * @generated from message land.gno.gnomobile.v1.GenerateRecoveryPhrase_Reply
 */
export const GenerateRecoveryPhrase_Reply = proto3.makeMessageType(
  "land.gno.gnomobile.v1.GenerateRecoveryPhrase_Reply",
  () => [
    { no: 1, name: "Phrase", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message land.gno.gnomobile.v1.Query_Request
 */
export const Query_Request = proto3.makeMessageType(
  "land.gno.gnomobile.v1.Query_Request",
  () => [
    { no: 1, name: "Path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message land.gno.gnomobile.v1.Query_Reply
 */
export const Query_Reply = proto3.makeMessageType(
  "land.gno.gnomobile.v1.Query_Reply",
  () => [
    { no: 1, name: "Result", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message land.gno.gnomobile.v1.Call_Request
 */
export const Call_Request = proto3.makeMessageType(
  "land.gno.gnomobile.v1.Call_Request",
  () => [
    { no: 1, name: "PackagePath", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Fnc", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Args", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "GasFee", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "GasWanted", kind: "scalar", T: 18 /* ScalarType.SINT64 */ },
    { no: 6, name: "Send", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "Memo", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message land.gno.gnomobile.v1.Call_Reply
 */
export const Call_Reply = proto3.makeMessageType(
  "land.gno.gnomobile.v1.Call_Reply",
  () => [
    { no: 1, name: "Result", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

