// @generated by protoc-gen-es v1.3.1
// @generated from file rpc.proto (package land.gno.gnomobile.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum land.gno.gnomobile.v1.KeyType
 */
export declare enum KeyType {
  /**
   * @generated from enum value: TypeLocal = 0;
   */
  TypeLocal = 0,

  /**
   * @generated from enum value: TypeLedger = 1;
   */
  TypeLedger = 1,

  /**
   * @generated from enum value: TypeOffline = 2;
   */
  TypeOffline = 2,

  /**
   * @generated from enum value: TypeMulti = 3;
   */
  TypeMulti = 3,
}

/**
 * ----------------
 * Special errors
 * ----------------
 *
 * @generated from enum land.gno.gnomobile.v1.ErrCode
 */
export declare enum ErrCode {
  /**
   * default value, should never be set manually
   *
   * @generated from enum value: Undefined = 0;
   */
  Undefined = 0,

  /**
   * indicates that you plan to create an error later
   *
   * @generated from enum value: TODO = 1;
   */
  TODO = 1,

  /**
   * indicates that a method is not implemented yet
   *
   * @generated from enum value: ErrNotImplemented = 2;
   */
  ErrNotImplemented = 2,

  /**
   * indicates an unknown error (without Code), i.e. in gRPC
   *
   * @generated from enum value: ErrInternal = 3;
   */
  ErrInternal = 3,

  /**
   * @generated from enum value: ErrInvalidInput = 100;
   */
  ErrInvalidInput = 100,

  /**
   * @generated from enum value: ErrBridgeInterrupted = 101;
   */
  ErrBridgeInterrupted = 101,

  /**
   * @generated from enum value: ErrMissingInput = 102;
   */
  ErrMissingInput = 102,

  /**
   * @generated from enum value: ErrSerialization = 103;
   */
  ErrSerialization = 103,

  /**
   * @generated from enum value: ErrDeserialization = 104;
   */
  ErrDeserialization = 104,

  /**
   * @generated from enum value: ErrCryptoKeyTypeUnknown = 105;
   */
  ErrCryptoKeyTypeUnknown = 105,

  /**
   * @generated from enum value: ErrCryptoKeyNotFound = 106;
   */
  ErrCryptoKeyNotFound = 106,

  /**
   * @generated from enum value: ErrNoActiveAccount = 107;
   */
  ErrNoActiveAccount = 107,

  /**
   * @generated from enum value: ErrRunGRPCServer = 108;
   */
  ErrRunGRPCServer = 108,
}

/**
 * @generated from message land.gno.gnomobile.v1.KeyInfo
 */
export declare class KeyInfo extends Message<KeyInfo> {
  /**
   * @generated from field: land.gno.gnomobile.v1.KeyType type = 1;
   */
  type: KeyType;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: bytes pubKey = 3;
   */
  pubKey: Uint8Array;

  /**
   * @generated from field: bytes address = 4;
   */
  address: Uint8Array;

  constructor(data?: PartialMessage<KeyInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.KeyInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KeyInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KeyInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KeyInfo;

  static equals(a: KeyInfo | PlainMessage<KeyInfo> | undefined, b: KeyInfo | PlainMessage<KeyInfo> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.ListKeyInfo
 */
export declare class ListKeyInfo extends Message<ListKeyInfo> {
  constructor(data?: PartialMessage<ListKeyInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.ListKeyInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListKeyInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListKeyInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListKeyInfo;

  static equals(a: ListKeyInfo | PlainMessage<ListKeyInfo> | undefined, b: ListKeyInfo | PlainMessage<ListKeyInfo> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.ListKeyInfo.Request
 */
export declare class ListKeyInfo_Request extends Message<ListKeyInfo_Request> {
  constructor(data?: PartialMessage<ListKeyInfo_Request>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.ListKeyInfo.Request";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListKeyInfo_Request;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListKeyInfo_Request;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListKeyInfo_Request;

  static equals(a: ListKeyInfo_Request | PlainMessage<ListKeyInfo_Request> | undefined, b: ListKeyInfo_Request | PlainMessage<ListKeyInfo_Request> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.ListKeyInfo.Reply
 */
export declare class ListKeyInfo_Reply extends Message<ListKeyInfo_Reply> {
  /**
   * @generated from field: repeated land.gno.gnomobile.v1.KeyInfo keys = 1;
   */
  keys: KeyInfo[];

  constructor(data?: PartialMessage<ListKeyInfo_Reply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.ListKeyInfo.Reply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListKeyInfo_Reply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListKeyInfo_Reply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListKeyInfo_Reply;

  static equals(a: ListKeyInfo_Reply | PlainMessage<ListKeyInfo_Reply> | undefined, b: ListKeyInfo_Reply | PlainMessage<ListKeyInfo_Reply> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.CreateAccount
 */
export declare class CreateAccount extends Message<CreateAccount> {
  constructor(data?: PartialMessage<CreateAccount>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.CreateAccount";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateAccount;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateAccount;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateAccount;

  static equals(a: CreateAccount | PlainMessage<CreateAccount> | undefined, b: CreateAccount | PlainMessage<CreateAccount> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.CreateAccount.Request
 */
export declare class CreateAccount_Request extends Message<CreateAccount_Request> {
  /**
   * @generated from field: string nameOrBech32 = 1;
   */
  nameOrBech32: string;

  /**
   * @generated from field: string mnemonic = 2;
   */
  mnemonic: string;

  /**
   * @generated from field: string bip39Passwd = 3;
   */
  bip39Passwd: string;

  /**
   * @generated from field: string password = 4;
   */
  password: string;

  /**
   * @generated from field: uint32 account = 5;
   */
  account: number;

  /**
   * @generated from field: uint32 index = 6;
   */
  index: number;

  constructor(data?: PartialMessage<CreateAccount_Request>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.CreateAccount.Request";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateAccount_Request;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateAccount_Request;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateAccount_Request;

  static equals(a: CreateAccount_Request | PlainMessage<CreateAccount_Request> | undefined, b: CreateAccount_Request | PlainMessage<CreateAccount_Request> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.CreateAccount.Reply
 */
export declare class CreateAccount_Reply extends Message<CreateAccount_Reply> {
  /**
   * @generated from field: land.gno.gnomobile.v1.KeyInfo key = 1;
   */
  key?: KeyInfo;

  constructor(data?: PartialMessage<CreateAccount_Reply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.CreateAccount.Reply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateAccount_Reply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateAccount_Reply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateAccount_Reply;

  static equals(a: CreateAccount_Reply | PlainMessage<CreateAccount_Reply> | undefined, b: CreateAccount_Reply | PlainMessage<CreateAccount_Reply> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.SelectAccount
 */
export declare class SelectAccount extends Message<SelectAccount> {
  constructor(data?: PartialMessage<SelectAccount>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.SelectAccount";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SelectAccount;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SelectAccount;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SelectAccount;

  static equals(a: SelectAccount | PlainMessage<SelectAccount> | undefined, b: SelectAccount | PlainMessage<SelectAccount> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.SelectAccount.Request
 */
export declare class SelectAccount_Request extends Message<SelectAccount_Request> {
  /**
   * @generated from field: string nameOrBech32 = 1;
   */
  nameOrBech32: string;

  constructor(data?: PartialMessage<SelectAccount_Request>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.SelectAccount.Request";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SelectAccount_Request;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SelectAccount_Request;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SelectAccount_Request;

  static equals(a: SelectAccount_Request | PlainMessage<SelectAccount_Request> | undefined, b: SelectAccount_Request | PlainMessage<SelectAccount_Request> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.SelectAccount.Reply
 */
export declare class SelectAccount_Reply extends Message<SelectAccount_Reply> {
  /**
   * @generated from field: land.gno.gnomobile.v1.KeyInfo key = 1;
   */
  key?: KeyInfo;

  constructor(data?: PartialMessage<SelectAccount_Reply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.SelectAccount.Reply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SelectAccount_Reply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SelectAccount_Reply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SelectAccount_Reply;

  static equals(a: SelectAccount_Reply | PlainMessage<SelectAccount_Reply> | undefined, b: SelectAccount_Reply | PlainMessage<SelectAccount_Reply> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.GetActiveAccount
 */
export declare class GetActiveAccount extends Message<GetActiveAccount> {
  constructor(data?: PartialMessage<GetActiveAccount>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.GetActiveAccount";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetActiveAccount;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetActiveAccount;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetActiveAccount;

  static equals(a: GetActiveAccount | PlainMessage<GetActiveAccount> | undefined, b: GetActiveAccount | PlainMessage<GetActiveAccount> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.GetActiveAccount.Request
 */
export declare class GetActiveAccount_Request extends Message<GetActiveAccount_Request> {
  constructor(data?: PartialMessage<GetActiveAccount_Request>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.GetActiveAccount.Request";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetActiveAccount_Request;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetActiveAccount_Request;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetActiveAccount_Request;

  static equals(a: GetActiveAccount_Request | PlainMessage<GetActiveAccount_Request> | undefined, b: GetActiveAccount_Request | PlainMessage<GetActiveAccount_Request> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.GetActiveAccount.Reply
 */
export declare class GetActiveAccount_Reply extends Message<GetActiveAccount_Reply> {
  /**
   * @generated from field: land.gno.gnomobile.v1.KeyInfo key = 1;
   */
  key?: KeyInfo;

  constructor(data?: PartialMessage<GetActiveAccount_Reply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.GetActiveAccount.Reply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetActiveAccount_Reply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetActiveAccount_Reply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetActiveAccount_Reply;

  static equals(a: GetActiveAccount_Reply | PlainMessage<GetActiveAccount_Reply> | undefined, b: GetActiveAccount_Reply | PlainMessage<GetActiveAccount_Reply> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.HelloRequest
 */
export declare class HelloRequest extends Message<HelloRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  constructor(data?: PartialMessage<HelloRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.HelloRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HelloRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HelloRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HelloRequest;

  static equals(a: HelloRequest | PlainMessage<HelloRequest> | undefined, b: HelloRequest | PlainMessage<HelloRequest> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.HelloReply
 */
export declare class HelloReply extends Message<HelloReply> {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string;

  constructor(data?: PartialMessage<HelloReply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.HelloReply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HelloReply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HelloReply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HelloReply;

  static equals(a: HelloReply | PlainMessage<HelloReply> | undefined, b: HelloReply | PlainMessage<HelloReply> | undefined): boolean;
}

/**
 * @generated from message land.gno.gnomobile.v1.ErrDetails
 */
export declare class ErrDetails extends Message<ErrDetails> {
  /**
   * @generated from field: repeated land.gno.gnomobile.v1.ErrCode codes = 1;
   */
  codes: ErrCode[];

  constructor(data?: PartialMessage<ErrDetails>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "land.gno.gnomobile.v1.ErrDetails";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ErrDetails;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ErrDetails;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ErrDetails;

  static equals(a: ErrDetails | PlainMessage<ErrDetails> | undefined, b: ErrDetails | PlainMessage<ErrDetails> | undefined): boolean;
}

