// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: rpc.proto

package rpcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	rpc "github.com/gnolang/gnomobile/service/rpc"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// GnomobileServiceName is the fully-qualified name of the GnomobileService service.
	GnomobileServiceName = "land.gno.gnomobile.v1.GnomobileService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GnomobileServiceSetRemoteProcedure is the fully-qualified name of the GnomobileService's
	// SetRemote RPC.
	GnomobileServiceSetRemoteProcedure = "/land.gno.gnomobile.v1.GnomobileService/SetRemote"
	// GnomobileServiceSetChainIDProcedure is the fully-qualified name of the GnomobileService's
	// SetChainID RPC.
	GnomobileServiceSetChainIDProcedure = "/land.gno.gnomobile.v1.GnomobileService/SetChainID"
	// GnomobileServiceGenerateRecoveryPhraseProcedure is the fully-qualified name of the
	// GnomobileService's GenerateRecoveryPhrase RPC.
	GnomobileServiceGenerateRecoveryPhraseProcedure = "/land.gno.gnomobile.v1.GnomobileService/GenerateRecoveryPhrase"
	// GnomobileServiceListKeyInfoProcedure is the fully-qualified name of the GnomobileService's
	// ListKeyInfo RPC.
	GnomobileServiceListKeyInfoProcedure = "/land.gno.gnomobile.v1.GnomobileService/ListKeyInfo"
	// GnomobileServiceGetKeyInfoByNameProcedure is the fully-qualified name of the GnomobileService's
	// GetKeyInfoByName RPC.
	GnomobileServiceGetKeyInfoByNameProcedure = "/land.gno.gnomobile.v1.GnomobileService/GetKeyInfoByName"
	// GnomobileServiceGetKeyInfoByAddressProcedure is the fully-qualified name of the
	// GnomobileService's GetKeyInfoByAddress RPC.
	GnomobileServiceGetKeyInfoByAddressProcedure = "/land.gno.gnomobile.v1.GnomobileService/GetKeyInfoByAddress"
	// GnomobileServiceGetKeyInfoByNameOrAddressProcedure is the fully-qualified name of the
	// GnomobileService's GetKeyInfoByNameOrAddress RPC.
	GnomobileServiceGetKeyInfoByNameOrAddressProcedure = "/land.gno.gnomobile.v1.GnomobileService/GetKeyInfoByNameOrAddress"
	// GnomobileServiceCreateAccountProcedure is the fully-qualified name of the GnomobileService's
	// CreateAccount RPC.
	GnomobileServiceCreateAccountProcedure = "/land.gno.gnomobile.v1.GnomobileService/CreateAccount"
	// GnomobileServiceSelectAccountProcedure is the fully-qualified name of the GnomobileService's
	// SelectAccount RPC.
	GnomobileServiceSelectAccountProcedure = "/land.gno.gnomobile.v1.GnomobileService/SelectAccount"
	// GnomobileServiceSetPasswordProcedure is the fully-qualified name of the GnomobileService's
	// SetPassword RPC.
	GnomobileServiceSetPasswordProcedure = "/land.gno.gnomobile.v1.GnomobileService/SetPassword"
	// GnomobileServiceGetActiveAccountProcedure is the fully-qualified name of the GnomobileService's
	// GetActiveAccount RPC.
	GnomobileServiceGetActiveAccountProcedure = "/land.gno.gnomobile.v1.GnomobileService/GetActiveAccount"
	// GnomobileServiceQueryAccountProcedure is the fully-qualified name of the GnomobileService's
	// QueryAccount RPC.
	GnomobileServiceQueryAccountProcedure = "/land.gno.gnomobile.v1.GnomobileService/QueryAccount"
	// GnomobileServiceDeleteAccountProcedure is the fully-qualified name of the GnomobileService's
	// DeleteAccount RPC.
	GnomobileServiceDeleteAccountProcedure = "/land.gno.gnomobile.v1.GnomobileService/DeleteAccount"
	// GnomobileServiceQueryProcedure is the fully-qualified name of the GnomobileService's Query RPC.
	GnomobileServiceQueryProcedure = "/land.gno.gnomobile.v1.GnomobileService/Query"
	// GnomobileServiceRenderProcedure is the fully-qualified name of the GnomobileService's Render RPC.
	GnomobileServiceRenderProcedure = "/land.gno.gnomobile.v1.GnomobileService/Render"
	// GnomobileServiceQEvalProcedure is the fully-qualified name of the GnomobileService's QEval RPC.
	GnomobileServiceQEvalProcedure = "/land.gno.gnomobile.v1.GnomobileService/QEval"
	// GnomobileServiceCallProcedure is the fully-qualified name of the GnomobileService's Call RPC.
	GnomobileServiceCallProcedure = "/land.gno.gnomobile.v1.GnomobileService/Call"
	// GnomobileServiceAddressToBech32Procedure is the fully-qualified name of the GnomobileService's
	// AddressToBech32 RPC.
	GnomobileServiceAddressToBech32Procedure = "/land.gno.gnomobile.v1.GnomobileService/AddressToBech32"
	// GnomobileServiceAddressFromBech32Procedure is the fully-qualified name of the GnomobileService's
	// AddressFromBech32 RPC.
	GnomobileServiceAddressFromBech32Procedure = "/land.gno.gnomobile.v1.GnomobileService/AddressFromBech32"
	// GnomobileServiceHelloProcedure is the fully-qualified name of the GnomobileService's Hello RPC.
	GnomobileServiceHelloProcedure = "/land.gno.gnomobile.v1.GnomobileService/Hello"
	// GnomobileServiceHelloStreamProcedure is the fully-qualified name of the GnomobileService's
	// HelloStream RPC.
	GnomobileServiceHelloStreamProcedure = "/land.gno.gnomobile.v1.GnomobileService/HelloStream"
)

// GnomobileServiceClient is a client for the land.gno.gnomobile.v1.GnomobileService service.
type GnomobileServiceClient interface {
	// Set the connection addresse for the remote node. If you don't call this,
	// the default is "127.0.0.1:26657"
	SetRemote(context.Context, *connect.Request[rpc.SetRemoteRequest]) (*connect.Response[rpc.SetRemoteResponse], error)
	// Set the chain ID for the remote node. If you don't call this, the default
	// is "dev"
	SetChainID(context.Context, *connect.Request[rpc.SetChainIDRequest]) (*connect.Response[rpc.SetChainIDResponse], error)
	// Generate a recovery phrase of BIP39 mnemonic words using entropy from the
	// crypto library random number generator. This can be used as the mnemonic in
	// CreateAccount.
	GenerateRecoveryPhrase(context.Context, *connect.Request[rpc.GenerateRecoveryPhraseRequest]) (*connect.Response[rpc.GenerateRecoveryPhraseResponse], error)
	// Get the information for all keys in the keybase
	ListKeyInfo(context.Context, *connect.Request[rpc.ListKeyInfoRequest]) (*connect.Response[rpc.ListKeyInfoResponse], error)
	// Get the information for the key in the keybase with the given name.
	// If the key doesn't exist, then return ErrCryptoKeyNotFound.
	GetKeyInfoByName(context.Context, *connect.Request[rpc.GetKeyInfoByNameRequest]) (*connect.Response[rpc.GetKeyInfoByNameResponse], error)
	// Get the information for the key in the keybase with the given address.
	// If the key doesn't exist, then return ErrCryptoKeyNotFound.
	GetKeyInfoByAddress(context.Context, *connect.Request[rpc.GetKeyInfoByAddressRequest]) (*connect.Response[rpc.GetKeyInfoByAddressResponse], error)
	// Get the information for the key in the keybase with the given name or bech32 string address.
	// If the key doesn't exist, then return ErrCryptoKeyNotFound.
	GetKeyInfoByNameOrAddress(context.Context, *connect.Request[rpc.GetKeyInfoByNameOrAddressRequest]) (*connect.Response[rpc.GetKeyInfoByNameOrAddressResponse], error)
	// Create a new account the keybase using the name an password specified by SetAccount.
	// If an account with the same name already exists in the keybase,
	// this replaces it. (If you don't want to replace it, then it's your responsibility
	// to use GetKeyInfoByName to check if it exists before calling this.)
	CreateAccount(context.Context, *connect.Request[rpc.CreateAccountRequest]) (*connect.Response[rpc.CreateAccountResponse], error)
	// SelectAccount selects the active account to use for later operations
	SelectAccount(context.Context, *connect.Request[rpc.SelectAccountRequest]) (*connect.Response[rpc.SelectAccountResponse], error)
	// Set the password for the account in the keybase, used for later operations
	SetPassword(context.Context, *connect.Request[rpc.SetPasswordRequest]) (*connect.Response[rpc.SetPasswordResponse], error)
	// GetActiveAccount gets the active account which was set by SelectAccount.
	// If there is no active account, then return ErrNoActiveAccount.
	// (To check if there is an active account, use ListKeyInfo and check the
	// length of the result.)
	GetActiveAccount(context.Context, *connect.Request[rpc.GetActiveAccountRequest]) (*connect.Response[rpc.GetActiveAccountResponse], error)
	// QueryAccount retrieves account information from the blockchain for a given
	// address.
	QueryAccount(context.Context, *connect.Request[rpc.QueryAccountRequest]) (*connect.Response[rpc.QueryAccountResponse], error)
	// DeleteAccount deletes the account with the given name, using the password
	// to ensure access. However, if skip_password is true, then ignore the
	// password. If the account doesn't exist, then return ErrCryptoKeyNotFound.
	// If the password is wrong, then return ErrDecryptionFailed.
	DeleteAccount(context.Context, *connect.Request[rpc.DeleteAccountRequest]) (*connect.Response[rpc.DeleteAccountResponse], error)
	// Make an ABCI query to the remote node.
	Query(context.Context, *connect.Request[rpc.QueryRequest]) (*connect.Response[rpc.QueryResponse], error)
	// Render calls the Render function for package_path with optional args. The
	// package path should include the prefix like "gno.land/". This is similar to
	// using a browser URL <testnet>/<pkgPath>:<args> where <pkgPath> doesn't have
	// the prefix like "gno.land/".
	Render(context.Context, *connect.Request[rpc.RenderRequest]) (*connect.Response[rpc.RenderResponse], error)
	// QEval evaluates the given expression with the realm code at package_path.
	// The package path should include the prefix like "gno.land/". The expression
	// is usually a function call like "GetBoardIDFromName(\"testboard\")". The
	// return value is a typed expression like
	// "(1 gno.land/r/demo/boards.BoardID)\n(true bool)".
	QEval(context.Context, *connect.Request[rpc.QEvalRequest]) (*connect.Response[rpc.QEvalResponse], error)
	// Call a specific realm function.
	Call(context.Context, *connect.Request[rpc.CallRequest]) (*connect.Response[rpc.CallResponse], error)
	// Convert a byte array address to a bech32 string address.
	AddressToBech32(context.Context, *connect.Request[rpc.AddressToBech32Request]) (*connect.Response[rpc.AddressToBech32Response], error)
	// Convert a bech32 string address to a byte array address.
	AddressFromBech32(context.Context, *connect.Request[rpc.AddressFromBech32Request]) (*connect.Response[rpc.AddressFromBech32Response], error)
	// Hello is for debug purposes
	Hello(context.Context, *connect.Request[rpc.HelloRequest]) (*connect.Response[rpc.HelloResponse], error)
	// HelloStream is for debug purposes
	HelloStream(context.Context, *connect.Request[rpc.HelloStreamRequest]) (*connect.ServerStreamForClient[rpc.HelloStreamResponse], error)
}

// NewGnomobileServiceClient constructs a client for the land.gno.gnomobile.v1.GnomobileService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGnomobileServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GnomobileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &gnomobileServiceClient{
		setRemote: connect.NewClient[rpc.SetRemoteRequest, rpc.SetRemoteResponse](
			httpClient,
			baseURL+GnomobileServiceSetRemoteProcedure,
			opts...,
		),
		setChainID: connect.NewClient[rpc.SetChainIDRequest, rpc.SetChainIDResponse](
			httpClient,
			baseURL+GnomobileServiceSetChainIDProcedure,
			opts...,
		),
		generateRecoveryPhrase: connect.NewClient[rpc.GenerateRecoveryPhraseRequest, rpc.GenerateRecoveryPhraseResponse](
			httpClient,
			baseURL+GnomobileServiceGenerateRecoveryPhraseProcedure,
			opts...,
		),
		listKeyInfo: connect.NewClient[rpc.ListKeyInfoRequest, rpc.ListKeyInfoResponse](
			httpClient,
			baseURL+GnomobileServiceListKeyInfoProcedure,
			opts...,
		),
		getKeyInfoByName: connect.NewClient[rpc.GetKeyInfoByNameRequest, rpc.GetKeyInfoByNameResponse](
			httpClient,
			baseURL+GnomobileServiceGetKeyInfoByNameProcedure,
			opts...,
		),
		getKeyInfoByAddress: connect.NewClient[rpc.GetKeyInfoByAddressRequest, rpc.GetKeyInfoByAddressResponse](
			httpClient,
			baseURL+GnomobileServiceGetKeyInfoByAddressProcedure,
			opts...,
		),
		getKeyInfoByNameOrAddress: connect.NewClient[rpc.GetKeyInfoByNameOrAddressRequest, rpc.GetKeyInfoByNameOrAddressResponse](
			httpClient,
			baseURL+GnomobileServiceGetKeyInfoByNameOrAddressProcedure,
			opts...,
		),
		createAccount: connect.NewClient[rpc.CreateAccountRequest, rpc.CreateAccountResponse](
			httpClient,
			baseURL+GnomobileServiceCreateAccountProcedure,
			opts...,
		),
		selectAccount: connect.NewClient[rpc.SelectAccountRequest, rpc.SelectAccountResponse](
			httpClient,
			baseURL+GnomobileServiceSelectAccountProcedure,
			opts...,
		),
		setPassword: connect.NewClient[rpc.SetPasswordRequest, rpc.SetPasswordResponse](
			httpClient,
			baseURL+GnomobileServiceSetPasswordProcedure,
			opts...,
		),
		getActiveAccount: connect.NewClient[rpc.GetActiveAccountRequest, rpc.GetActiveAccountResponse](
			httpClient,
			baseURL+GnomobileServiceGetActiveAccountProcedure,
			opts...,
		),
		queryAccount: connect.NewClient[rpc.QueryAccountRequest, rpc.QueryAccountResponse](
			httpClient,
			baseURL+GnomobileServiceQueryAccountProcedure,
			opts...,
		),
		deleteAccount: connect.NewClient[rpc.DeleteAccountRequest, rpc.DeleteAccountResponse](
			httpClient,
			baseURL+GnomobileServiceDeleteAccountProcedure,
			opts...,
		),
		query: connect.NewClient[rpc.QueryRequest, rpc.QueryResponse](
			httpClient,
			baseURL+GnomobileServiceQueryProcedure,
			opts...,
		),
		render: connect.NewClient[rpc.RenderRequest, rpc.RenderResponse](
			httpClient,
			baseURL+GnomobileServiceRenderProcedure,
			opts...,
		),
		qEval: connect.NewClient[rpc.QEvalRequest, rpc.QEvalResponse](
			httpClient,
			baseURL+GnomobileServiceQEvalProcedure,
			opts...,
		),
		call: connect.NewClient[rpc.CallRequest, rpc.CallResponse](
			httpClient,
			baseURL+GnomobileServiceCallProcedure,
			opts...,
		),
		addressToBech32: connect.NewClient[rpc.AddressToBech32Request, rpc.AddressToBech32Response](
			httpClient,
			baseURL+GnomobileServiceAddressToBech32Procedure,
			opts...,
		),
		addressFromBech32: connect.NewClient[rpc.AddressFromBech32Request, rpc.AddressFromBech32Response](
			httpClient,
			baseURL+GnomobileServiceAddressFromBech32Procedure,
			opts...,
		),
		hello: connect.NewClient[rpc.HelloRequest, rpc.HelloResponse](
			httpClient,
			baseURL+GnomobileServiceHelloProcedure,
			opts...,
		),
		helloStream: connect.NewClient[rpc.HelloStreamRequest, rpc.HelloStreamResponse](
			httpClient,
			baseURL+GnomobileServiceHelloStreamProcedure,
			opts...,
		),
	}
}

// gnomobileServiceClient implements GnomobileServiceClient.
type gnomobileServiceClient struct {
	setRemote                 *connect.Client[rpc.SetRemoteRequest, rpc.SetRemoteResponse]
	setChainID                *connect.Client[rpc.SetChainIDRequest, rpc.SetChainIDResponse]
	generateRecoveryPhrase    *connect.Client[rpc.GenerateRecoveryPhraseRequest, rpc.GenerateRecoveryPhraseResponse]
	listKeyInfo               *connect.Client[rpc.ListKeyInfoRequest, rpc.ListKeyInfoResponse]
	getKeyInfoByName          *connect.Client[rpc.GetKeyInfoByNameRequest, rpc.GetKeyInfoByNameResponse]
	getKeyInfoByAddress       *connect.Client[rpc.GetKeyInfoByAddressRequest, rpc.GetKeyInfoByAddressResponse]
	getKeyInfoByNameOrAddress *connect.Client[rpc.GetKeyInfoByNameOrAddressRequest, rpc.GetKeyInfoByNameOrAddressResponse]
	createAccount             *connect.Client[rpc.CreateAccountRequest, rpc.CreateAccountResponse]
	selectAccount             *connect.Client[rpc.SelectAccountRequest, rpc.SelectAccountResponse]
	setPassword               *connect.Client[rpc.SetPasswordRequest, rpc.SetPasswordResponse]
	getActiveAccount          *connect.Client[rpc.GetActiveAccountRequest, rpc.GetActiveAccountResponse]
	queryAccount              *connect.Client[rpc.QueryAccountRequest, rpc.QueryAccountResponse]
	deleteAccount             *connect.Client[rpc.DeleteAccountRequest, rpc.DeleteAccountResponse]
	query                     *connect.Client[rpc.QueryRequest, rpc.QueryResponse]
	render                    *connect.Client[rpc.RenderRequest, rpc.RenderResponse]
	qEval                     *connect.Client[rpc.QEvalRequest, rpc.QEvalResponse]
	call                      *connect.Client[rpc.CallRequest, rpc.CallResponse]
	addressToBech32           *connect.Client[rpc.AddressToBech32Request, rpc.AddressToBech32Response]
	addressFromBech32         *connect.Client[rpc.AddressFromBech32Request, rpc.AddressFromBech32Response]
	hello                     *connect.Client[rpc.HelloRequest, rpc.HelloResponse]
	helloStream               *connect.Client[rpc.HelloStreamRequest, rpc.HelloStreamResponse]
}

// SetRemote calls land.gno.gnomobile.v1.GnomobileService.SetRemote.
func (c *gnomobileServiceClient) SetRemote(ctx context.Context, req *connect.Request[rpc.SetRemoteRequest]) (*connect.Response[rpc.SetRemoteResponse], error) {
	return c.setRemote.CallUnary(ctx, req)
}

// SetChainID calls land.gno.gnomobile.v1.GnomobileService.SetChainID.
func (c *gnomobileServiceClient) SetChainID(ctx context.Context, req *connect.Request[rpc.SetChainIDRequest]) (*connect.Response[rpc.SetChainIDResponse], error) {
	return c.setChainID.CallUnary(ctx, req)
}

// GenerateRecoveryPhrase calls land.gno.gnomobile.v1.GnomobileService.GenerateRecoveryPhrase.
func (c *gnomobileServiceClient) GenerateRecoveryPhrase(ctx context.Context, req *connect.Request[rpc.GenerateRecoveryPhraseRequest]) (*connect.Response[rpc.GenerateRecoveryPhraseResponse], error) {
	return c.generateRecoveryPhrase.CallUnary(ctx, req)
}

// ListKeyInfo calls land.gno.gnomobile.v1.GnomobileService.ListKeyInfo.
func (c *gnomobileServiceClient) ListKeyInfo(ctx context.Context, req *connect.Request[rpc.ListKeyInfoRequest]) (*connect.Response[rpc.ListKeyInfoResponse], error) {
	return c.listKeyInfo.CallUnary(ctx, req)
}

// GetKeyInfoByName calls land.gno.gnomobile.v1.GnomobileService.GetKeyInfoByName.
func (c *gnomobileServiceClient) GetKeyInfoByName(ctx context.Context, req *connect.Request[rpc.GetKeyInfoByNameRequest]) (*connect.Response[rpc.GetKeyInfoByNameResponse], error) {
	return c.getKeyInfoByName.CallUnary(ctx, req)
}

// GetKeyInfoByAddress calls land.gno.gnomobile.v1.GnomobileService.GetKeyInfoByAddress.
func (c *gnomobileServiceClient) GetKeyInfoByAddress(ctx context.Context, req *connect.Request[rpc.GetKeyInfoByAddressRequest]) (*connect.Response[rpc.GetKeyInfoByAddressResponse], error) {
	return c.getKeyInfoByAddress.CallUnary(ctx, req)
}

// GetKeyInfoByNameOrAddress calls land.gno.gnomobile.v1.GnomobileService.GetKeyInfoByNameOrAddress.
func (c *gnomobileServiceClient) GetKeyInfoByNameOrAddress(ctx context.Context, req *connect.Request[rpc.GetKeyInfoByNameOrAddressRequest]) (*connect.Response[rpc.GetKeyInfoByNameOrAddressResponse], error) {
	return c.getKeyInfoByNameOrAddress.CallUnary(ctx, req)
}

// CreateAccount calls land.gno.gnomobile.v1.GnomobileService.CreateAccount.
func (c *gnomobileServiceClient) CreateAccount(ctx context.Context, req *connect.Request[rpc.CreateAccountRequest]) (*connect.Response[rpc.CreateAccountResponse], error) {
	return c.createAccount.CallUnary(ctx, req)
}

// SelectAccount calls land.gno.gnomobile.v1.GnomobileService.SelectAccount.
func (c *gnomobileServiceClient) SelectAccount(ctx context.Context, req *connect.Request[rpc.SelectAccountRequest]) (*connect.Response[rpc.SelectAccountResponse], error) {
	return c.selectAccount.CallUnary(ctx, req)
}

// SetPassword calls land.gno.gnomobile.v1.GnomobileService.SetPassword.
func (c *gnomobileServiceClient) SetPassword(ctx context.Context, req *connect.Request[rpc.SetPasswordRequest]) (*connect.Response[rpc.SetPasswordResponse], error) {
	return c.setPassword.CallUnary(ctx, req)
}

// GetActiveAccount calls land.gno.gnomobile.v1.GnomobileService.GetActiveAccount.
func (c *gnomobileServiceClient) GetActiveAccount(ctx context.Context, req *connect.Request[rpc.GetActiveAccountRequest]) (*connect.Response[rpc.GetActiveAccountResponse], error) {
	return c.getActiveAccount.CallUnary(ctx, req)
}

// QueryAccount calls land.gno.gnomobile.v1.GnomobileService.QueryAccount.
func (c *gnomobileServiceClient) QueryAccount(ctx context.Context, req *connect.Request[rpc.QueryAccountRequest]) (*connect.Response[rpc.QueryAccountResponse], error) {
	return c.queryAccount.CallUnary(ctx, req)
}

// DeleteAccount calls land.gno.gnomobile.v1.GnomobileService.DeleteAccount.
func (c *gnomobileServiceClient) DeleteAccount(ctx context.Context, req *connect.Request[rpc.DeleteAccountRequest]) (*connect.Response[rpc.DeleteAccountResponse], error) {
	return c.deleteAccount.CallUnary(ctx, req)
}

// Query calls land.gno.gnomobile.v1.GnomobileService.Query.
func (c *gnomobileServiceClient) Query(ctx context.Context, req *connect.Request[rpc.QueryRequest]) (*connect.Response[rpc.QueryResponse], error) {
	return c.query.CallUnary(ctx, req)
}

// Render calls land.gno.gnomobile.v1.GnomobileService.Render.
func (c *gnomobileServiceClient) Render(ctx context.Context, req *connect.Request[rpc.RenderRequest]) (*connect.Response[rpc.RenderResponse], error) {
	return c.render.CallUnary(ctx, req)
}

// QEval calls land.gno.gnomobile.v1.GnomobileService.QEval.
func (c *gnomobileServiceClient) QEval(ctx context.Context, req *connect.Request[rpc.QEvalRequest]) (*connect.Response[rpc.QEvalResponse], error) {
	return c.qEval.CallUnary(ctx, req)
}

// Call calls land.gno.gnomobile.v1.GnomobileService.Call.
func (c *gnomobileServiceClient) Call(ctx context.Context, req *connect.Request[rpc.CallRequest]) (*connect.Response[rpc.CallResponse], error) {
	return c.call.CallUnary(ctx, req)
}

// AddressToBech32 calls land.gno.gnomobile.v1.GnomobileService.AddressToBech32.
func (c *gnomobileServiceClient) AddressToBech32(ctx context.Context, req *connect.Request[rpc.AddressToBech32Request]) (*connect.Response[rpc.AddressToBech32Response], error) {
	return c.addressToBech32.CallUnary(ctx, req)
}

// AddressFromBech32 calls land.gno.gnomobile.v1.GnomobileService.AddressFromBech32.
func (c *gnomobileServiceClient) AddressFromBech32(ctx context.Context, req *connect.Request[rpc.AddressFromBech32Request]) (*connect.Response[rpc.AddressFromBech32Response], error) {
	return c.addressFromBech32.CallUnary(ctx, req)
}

// Hello calls land.gno.gnomobile.v1.GnomobileService.Hello.
func (c *gnomobileServiceClient) Hello(ctx context.Context, req *connect.Request[rpc.HelloRequest]) (*connect.Response[rpc.HelloResponse], error) {
	return c.hello.CallUnary(ctx, req)
}

// HelloStream calls land.gno.gnomobile.v1.GnomobileService.HelloStream.
func (c *gnomobileServiceClient) HelloStream(ctx context.Context, req *connect.Request[rpc.HelloStreamRequest]) (*connect.ServerStreamForClient[rpc.HelloStreamResponse], error) {
	return c.helloStream.CallServerStream(ctx, req)
}

// GnomobileServiceHandler is an implementation of the land.gno.gnomobile.v1.GnomobileService
// service.
type GnomobileServiceHandler interface {
	// Set the connection addresse for the remote node. If you don't call this,
	// the default is "127.0.0.1:26657"
	SetRemote(context.Context, *connect.Request[rpc.SetRemoteRequest]) (*connect.Response[rpc.SetRemoteResponse], error)
	// Set the chain ID for the remote node. If you don't call this, the default
	// is "dev"
	SetChainID(context.Context, *connect.Request[rpc.SetChainIDRequest]) (*connect.Response[rpc.SetChainIDResponse], error)
	// Generate a recovery phrase of BIP39 mnemonic words using entropy from the
	// crypto library random number generator. This can be used as the mnemonic in
	// CreateAccount.
	GenerateRecoveryPhrase(context.Context, *connect.Request[rpc.GenerateRecoveryPhraseRequest]) (*connect.Response[rpc.GenerateRecoveryPhraseResponse], error)
	// Get the information for all keys in the keybase
	ListKeyInfo(context.Context, *connect.Request[rpc.ListKeyInfoRequest]) (*connect.Response[rpc.ListKeyInfoResponse], error)
	// Get the information for the key in the keybase with the given name.
	// If the key doesn't exist, then return ErrCryptoKeyNotFound.
	GetKeyInfoByName(context.Context, *connect.Request[rpc.GetKeyInfoByNameRequest]) (*connect.Response[rpc.GetKeyInfoByNameResponse], error)
	// Get the information for the key in the keybase with the given address.
	// If the key doesn't exist, then return ErrCryptoKeyNotFound.
	GetKeyInfoByAddress(context.Context, *connect.Request[rpc.GetKeyInfoByAddressRequest]) (*connect.Response[rpc.GetKeyInfoByAddressResponse], error)
	// Get the information for the key in the keybase with the given name or bech32 string address.
	// If the key doesn't exist, then return ErrCryptoKeyNotFound.
	GetKeyInfoByNameOrAddress(context.Context, *connect.Request[rpc.GetKeyInfoByNameOrAddressRequest]) (*connect.Response[rpc.GetKeyInfoByNameOrAddressResponse], error)
	// Create a new account the keybase using the name an password specified by SetAccount.
	// If an account with the same name already exists in the keybase,
	// this replaces it. (If you don't want to replace it, then it's your responsibility
	// to use GetKeyInfoByName to check if it exists before calling this.)
	CreateAccount(context.Context, *connect.Request[rpc.CreateAccountRequest]) (*connect.Response[rpc.CreateAccountResponse], error)
	// SelectAccount selects the active account to use for later operations
	SelectAccount(context.Context, *connect.Request[rpc.SelectAccountRequest]) (*connect.Response[rpc.SelectAccountResponse], error)
	// Set the password for the account in the keybase, used for later operations
	SetPassword(context.Context, *connect.Request[rpc.SetPasswordRequest]) (*connect.Response[rpc.SetPasswordResponse], error)
	// GetActiveAccount gets the active account which was set by SelectAccount.
	// If there is no active account, then return ErrNoActiveAccount.
	// (To check if there is an active account, use ListKeyInfo and check the
	// length of the result.)
	GetActiveAccount(context.Context, *connect.Request[rpc.GetActiveAccountRequest]) (*connect.Response[rpc.GetActiveAccountResponse], error)
	// QueryAccount retrieves account information from the blockchain for a given
	// address.
	QueryAccount(context.Context, *connect.Request[rpc.QueryAccountRequest]) (*connect.Response[rpc.QueryAccountResponse], error)
	// DeleteAccount deletes the account with the given name, using the password
	// to ensure access. However, if skip_password is true, then ignore the
	// password. If the account doesn't exist, then return ErrCryptoKeyNotFound.
	// If the password is wrong, then return ErrDecryptionFailed.
	DeleteAccount(context.Context, *connect.Request[rpc.DeleteAccountRequest]) (*connect.Response[rpc.DeleteAccountResponse], error)
	// Make an ABCI query to the remote node.
	Query(context.Context, *connect.Request[rpc.QueryRequest]) (*connect.Response[rpc.QueryResponse], error)
	// Render calls the Render function for package_path with optional args. The
	// package path should include the prefix like "gno.land/". This is similar to
	// using a browser URL <testnet>/<pkgPath>:<args> where <pkgPath> doesn't have
	// the prefix like "gno.land/".
	Render(context.Context, *connect.Request[rpc.RenderRequest]) (*connect.Response[rpc.RenderResponse], error)
	// QEval evaluates the given expression with the realm code at package_path.
	// The package path should include the prefix like "gno.land/". The expression
	// is usually a function call like "GetBoardIDFromName(\"testboard\")". The
	// return value is a typed expression like
	// "(1 gno.land/r/demo/boards.BoardID)\n(true bool)".
	QEval(context.Context, *connect.Request[rpc.QEvalRequest]) (*connect.Response[rpc.QEvalResponse], error)
	// Call a specific realm function.
	Call(context.Context, *connect.Request[rpc.CallRequest]) (*connect.Response[rpc.CallResponse], error)
	// Convert a byte array address to a bech32 string address.
	AddressToBech32(context.Context, *connect.Request[rpc.AddressToBech32Request]) (*connect.Response[rpc.AddressToBech32Response], error)
	// Convert a bech32 string address to a byte array address.
	AddressFromBech32(context.Context, *connect.Request[rpc.AddressFromBech32Request]) (*connect.Response[rpc.AddressFromBech32Response], error)
	// Hello is for debug purposes
	Hello(context.Context, *connect.Request[rpc.HelloRequest]) (*connect.Response[rpc.HelloResponse], error)
	// HelloStream is for debug purposes
	HelloStream(context.Context, *connect.Request[rpc.HelloStreamRequest], *connect.ServerStream[rpc.HelloStreamResponse]) error
}

// NewGnomobileServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGnomobileServiceHandler(svc GnomobileServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gnomobileServiceSetRemoteHandler := connect.NewUnaryHandler(
		GnomobileServiceSetRemoteProcedure,
		svc.SetRemote,
		opts...,
	)
	gnomobileServiceSetChainIDHandler := connect.NewUnaryHandler(
		GnomobileServiceSetChainIDProcedure,
		svc.SetChainID,
		opts...,
	)
	gnomobileServiceGenerateRecoveryPhraseHandler := connect.NewUnaryHandler(
		GnomobileServiceGenerateRecoveryPhraseProcedure,
		svc.GenerateRecoveryPhrase,
		opts...,
	)
	gnomobileServiceListKeyInfoHandler := connect.NewUnaryHandler(
		GnomobileServiceListKeyInfoProcedure,
		svc.ListKeyInfo,
		opts...,
	)
	gnomobileServiceGetKeyInfoByNameHandler := connect.NewUnaryHandler(
		GnomobileServiceGetKeyInfoByNameProcedure,
		svc.GetKeyInfoByName,
		opts...,
	)
	gnomobileServiceGetKeyInfoByAddressHandler := connect.NewUnaryHandler(
		GnomobileServiceGetKeyInfoByAddressProcedure,
		svc.GetKeyInfoByAddress,
		opts...,
	)
	gnomobileServiceGetKeyInfoByNameOrAddressHandler := connect.NewUnaryHandler(
		GnomobileServiceGetKeyInfoByNameOrAddressProcedure,
		svc.GetKeyInfoByNameOrAddress,
		opts...,
	)
	gnomobileServiceCreateAccountHandler := connect.NewUnaryHandler(
		GnomobileServiceCreateAccountProcedure,
		svc.CreateAccount,
		opts...,
	)
	gnomobileServiceSelectAccountHandler := connect.NewUnaryHandler(
		GnomobileServiceSelectAccountProcedure,
		svc.SelectAccount,
		opts...,
	)
	gnomobileServiceSetPasswordHandler := connect.NewUnaryHandler(
		GnomobileServiceSetPasswordProcedure,
		svc.SetPassword,
		opts...,
	)
	gnomobileServiceGetActiveAccountHandler := connect.NewUnaryHandler(
		GnomobileServiceGetActiveAccountProcedure,
		svc.GetActiveAccount,
		opts...,
	)
	gnomobileServiceQueryAccountHandler := connect.NewUnaryHandler(
		GnomobileServiceQueryAccountProcedure,
		svc.QueryAccount,
		opts...,
	)
	gnomobileServiceDeleteAccountHandler := connect.NewUnaryHandler(
		GnomobileServiceDeleteAccountProcedure,
		svc.DeleteAccount,
		opts...,
	)
	gnomobileServiceQueryHandler := connect.NewUnaryHandler(
		GnomobileServiceQueryProcedure,
		svc.Query,
		opts...,
	)
	gnomobileServiceRenderHandler := connect.NewUnaryHandler(
		GnomobileServiceRenderProcedure,
		svc.Render,
		opts...,
	)
	gnomobileServiceQEvalHandler := connect.NewUnaryHandler(
		GnomobileServiceQEvalProcedure,
		svc.QEval,
		opts...,
	)
	gnomobileServiceCallHandler := connect.NewUnaryHandler(
		GnomobileServiceCallProcedure,
		svc.Call,
		opts...,
	)
	gnomobileServiceAddressToBech32Handler := connect.NewUnaryHandler(
		GnomobileServiceAddressToBech32Procedure,
		svc.AddressToBech32,
		opts...,
	)
	gnomobileServiceAddressFromBech32Handler := connect.NewUnaryHandler(
		GnomobileServiceAddressFromBech32Procedure,
		svc.AddressFromBech32,
		opts...,
	)
	gnomobileServiceHelloHandler := connect.NewUnaryHandler(
		GnomobileServiceHelloProcedure,
		svc.Hello,
		opts...,
	)
	gnomobileServiceHelloStreamHandler := connect.NewServerStreamHandler(
		GnomobileServiceHelloStreamProcedure,
		svc.HelloStream,
		opts...,
	)
	return "/land.gno.gnomobile.v1.GnomobileService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GnomobileServiceSetRemoteProcedure:
			gnomobileServiceSetRemoteHandler.ServeHTTP(w, r)
		case GnomobileServiceSetChainIDProcedure:
			gnomobileServiceSetChainIDHandler.ServeHTTP(w, r)
		case GnomobileServiceGenerateRecoveryPhraseProcedure:
			gnomobileServiceGenerateRecoveryPhraseHandler.ServeHTTP(w, r)
		case GnomobileServiceListKeyInfoProcedure:
			gnomobileServiceListKeyInfoHandler.ServeHTTP(w, r)
		case GnomobileServiceGetKeyInfoByNameProcedure:
			gnomobileServiceGetKeyInfoByNameHandler.ServeHTTP(w, r)
		case GnomobileServiceGetKeyInfoByAddressProcedure:
			gnomobileServiceGetKeyInfoByAddressHandler.ServeHTTP(w, r)
		case GnomobileServiceGetKeyInfoByNameOrAddressProcedure:
			gnomobileServiceGetKeyInfoByNameOrAddressHandler.ServeHTTP(w, r)
		case GnomobileServiceCreateAccountProcedure:
			gnomobileServiceCreateAccountHandler.ServeHTTP(w, r)
		case GnomobileServiceSelectAccountProcedure:
			gnomobileServiceSelectAccountHandler.ServeHTTP(w, r)
		case GnomobileServiceSetPasswordProcedure:
			gnomobileServiceSetPasswordHandler.ServeHTTP(w, r)
		case GnomobileServiceGetActiveAccountProcedure:
			gnomobileServiceGetActiveAccountHandler.ServeHTTP(w, r)
		case GnomobileServiceQueryAccountProcedure:
			gnomobileServiceQueryAccountHandler.ServeHTTP(w, r)
		case GnomobileServiceDeleteAccountProcedure:
			gnomobileServiceDeleteAccountHandler.ServeHTTP(w, r)
		case GnomobileServiceQueryProcedure:
			gnomobileServiceQueryHandler.ServeHTTP(w, r)
		case GnomobileServiceRenderProcedure:
			gnomobileServiceRenderHandler.ServeHTTP(w, r)
		case GnomobileServiceQEvalProcedure:
			gnomobileServiceQEvalHandler.ServeHTTP(w, r)
		case GnomobileServiceCallProcedure:
			gnomobileServiceCallHandler.ServeHTTP(w, r)
		case GnomobileServiceAddressToBech32Procedure:
			gnomobileServiceAddressToBech32Handler.ServeHTTP(w, r)
		case GnomobileServiceAddressFromBech32Procedure:
			gnomobileServiceAddressFromBech32Handler.ServeHTTP(w, r)
		case GnomobileServiceHelloProcedure:
			gnomobileServiceHelloHandler.ServeHTTP(w, r)
		case GnomobileServiceHelloStreamProcedure:
			gnomobileServiceHelloStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGnomobileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGnomobileServiceHandler struct{}

func (UnimplementedGnomobileServiceHandler) SetRemote(context.Context, *connect.Request[rpc.SetRemoteRequest]) (*connect.Response[rpc.SetRemoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.SetRemote is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) SetChainID(context.Context, *connect.Request[rpc.SetChainIDRequest]) (*connect.Response[rpc.SetChainIDResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.SetChainID is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) GenerateRecoveryPhrase(context.Context, *connect.Request[rpc.GenerateRecoveryPhraseRequest]) (*connect.Response[rpc.GenerateRecoveryPhraseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.GenerateRecoveryPhrase is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) ListKeyInfo(context.Context, *connect.Request[rpc.ListKeyInfoRequest]) (*connect.Response[rpc.ListKeyInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.ListKeyInfo is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) GetKeyInfoByName(context.Context, *connect.Request[rpc.GetKeyInfoByNameRequest]) (*connect.Response[rpc.GetKeyInfoByNameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.GetKeyInfoByName is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) GetKeyInfoByAddress(context.Context, *connect.Request[rpc.GetKeyInfoByAddressRequest]) (*connect.Response[rpc.GetKeyInfoByAddressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.GetKeyInfoByAddress is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) GetKeyInfoByNameOrAddress(context.Context, *connect.Request[rpc.GetKeyInfoByNameOrAddressRequest]) (*connect.Response[rpc.GetKeyInfoByNameOrAddressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.GetKeyInfoByNameOrAddress is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) CreateAccount(context.Context, *connect.Request[rpc.CreateAccountRequest]) (*connect.Response[rpc.CreateAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.CreateAccount is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) SelectAccount(context.Context, *connect.Request[rpc.SelectAccountRequest]) (*connect.Response[rpc.SelectAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.SelectAccount is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) SetPassword(context.Context, *connect.Request[rpc.SetPasswordRequest]) (*connect.Response[rpc.SetPasswordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.SetPassword is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) GetActiveAccount(context.Context, *connect.Request[rpc.GetActiveAccountRequest]) (*connect.Response[rpc.GetActiveAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.GetActiveAccount is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) QueryAccount(context.Context, *connect.Request[rpc.QueryAccountRequest]) (*connect.Response[rpc.QueryAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.QueryAccount is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) DeleteAccount(context.Context, *connect.Request[rpc.DeleteAccountRequest]) (*connect.Response[rpc.DeleteAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.DeleteAccount is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) Query(context.Context, *connect.Request[rpc.QueryRequest]) (*connect.Response[rpc.QueryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.Query is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) Render(context.Context, *connect.Request[rpc.RenderRequest]) (*connect.Response[rpc.RenderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.Render is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) QEval(context.Context, *connect.Request[rpc.QEvalRequest]) (*connect.Response[rpc.QEvalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.QEval is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) Call(context.Context, *connect.Request[rpc.CallRequest]) (*connect.Response[rpc.CallResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.Call is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) AddressToBech32(context.Context, *connect.Request[rpc.AddressToBech32Request]) (*connect.Response[rpc.AddressToBech32Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.AddressToBech32 is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) AddressFromBech32(context.Context, *connect.Request[rpc.AddressFromBech32Request]) (*connect.Response[rpc.AddressFromBech32Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.AddressFromBech32 is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) Hello(context.Context, *connect.Request[rpc.HelloRequest]) (*connect.Response[rpc.HelloResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.Hello is not implemented"))
}

func (UnimplementedGnomobileServiceHandler) HelloStream(context.Context, *connect.Request[rpc.HelloStreamRequest], *connect.ServerStream[rpc.HelloStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("land.gno.gnomobile.v1.GnomobileService.HelloStream is not implemented"))
}
